/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param employeeId
 * @param weekStart
 * @param acked
 * @param acknowledgedAt
 */
@Serializable

data class AttendanceWeek52Ack (

    @Contextual @SerialName(value = "employee_id")
    val employeeId: java.util.UUID,

    @Contextual @SerialName(value = "week_start")
    val weekStart: java.time.LocalDate,

    @SerialName(value = "acked")
    val acked: kotlin.Boolean,

    @Contextual @SerialName(value = "acknowledged_at")
    val acknowledgedAt: java.time.OffsetDateTime

) {


}
