/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.FinancialConfigSnapshot
import com.maintenance.api.client.model.PurchaseRequestExceptionInput
import com.maintenance.api.client.model.PurchaseRequestLineInput
import com.maintenance.api.client.model.PurchaseType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param branchId
 * @param vendorName
 * @param memo
 * @param config
 * @param purchaseType
 * @param equipmentId
 * @param workOrderId
 * @param statementEvidenceId
 * @param amountWon
 * @param lines
 * @param exceptions
 * @param shippingWon
 * @param discountWon
 */
@Serializable

data class CreatePurchaseRequest (

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @SerialName(value = "vendor_name")
    val vendorName: kotlin.String,

    @SerialName(value = "memo")
    val memo: kotlin.String,

    @SerialName(value = "config")
    val config: FinancialConfigSnapshot,

    @Contextual @SerialName(value = "purchase_type")
    val purchaseType: PurchaseType? = null,

    @Contextual @SerialName(value = "equipment_id")
    val equipmentId: java.util.UUID? = null,

    @Contextual @SerialName(value = "work_order_id")
    val workOrderId: java.util.UUID? = null,

    @Contextual @SerialName(value = "statement_evidence_id")
    val statementEvidenceId: java.util.UUID? = null,

    @SerialName(value = "amount_won")
    val amountWon: kotlin.Long? = null,

    @SerialName(value = "lines")
    val lines: kotlin.collections.List<PurchaseRequestLineInput>? = null,

    @SerialName(value = "exceptions")
    val exceptions: kotlin.collections.List<PurchaseRequestExceptionInput>? = null,

    @SerialName(value = "shipping_won")
    val shippingWon: kotlin.Long? = 0L,

    @SerialName(value = "discount_won")
    val discountWon: kotlin.Long? = 0L

) {


}
