/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.Null

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param unitId
 * @param caseId
 * @param kind
 * @param status
 * @param costMinor
 * @param saleAmountMinor
 * @param buyerName
 * @param completedBy
 * @param completedAt
 * @param financeGlPosting
 */
@Serializable

data class Equipment3rDisposition (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "unitId")
    val unitId: java.util.UUID,

    @Contextual @SerialName(value = "caseId")
    val caseId: java.util.UUID,

    @SerialName(value = "kind")
    val kind: Equipment3rDisposition.Kind,

    @SerialName(value = "status")
    val status: Equipment3rDisposition.Status,

    @SerialName(value = "costMinor")
    val costMinor: kotlin.Long?,

    @SerialName(value = "saleAmountMinor")
    val saleAmountMinor: kotlin.Long?,

    @SerialName(value = "buyerName")
    val buyerName: kotlin.String?,

    @Contextual @SerialName(value = "completedBy")
    val completedBy: java.util.UUID?,

    @Contextual @SerialName(value = "completedAt")
    val completedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "financeGlPosting")
    val financeGlPosting: Null

) {

    /**
     *
     *
     * Values: REPAIR,REFURBISH,RESALE,REDEPLOY
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "REPAIR") REPAIR("REPAIR"),
        @SerialName(value = "REFURBISH") REFURBISH("REFURBISH"),
        @SerialName(value = "RESALE") RESALE("RESALE"),
        @SerialName(value = "REDEPLOY") REDEPLOY("REDEPLOY");
    }
    /**
     *
     *
     * Values: OPEN,COMPLETED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "OPEN") OPEN("OPEN"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED");
    }

}
