/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param decision
 * @param decidedBy
 * @param decidedAt
 * @param reason
 */
@Serializable

data class Equipment3rApprovalRecord (

    @SerialName(value = "decision")
    val decision: Equipment3rApprovalRecord.Decision,

    @Contextual @SerialName(value = "decidedBy")
    val decidedBy: java.util.UUID,

    @Contextual @SerialName(value = "decidedAt")
    val decidedAt: java.time.OffsetDateTime,

    @SerialName(value = "reason")
    val reason: kotlin.String? = null

) {

    /**
     *
     *
     * Values: APPROVED,DECLINED
     */
    @Serializable
    enum class Decision(val value: kotlin.String) {
        @SerialName(value = "APPROVED") APPROVED("APPROVED"),
        @SerialName(value = "DECLINED") DECLINED("DECLINED");
    }

}
