/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param runs
 * @param appliedRuns
 * @param inputRows
 * @param candidateRows
 * @param preservedRows
 * @param ledgerRows
 * @param latestImportAt
 */
@Serializable

data class HrReadinessSummaryImports (

    @SerialName(value = "runs")
    val runs: kotlin.Long,

    @SerialName(value = "applied_runs")
    val appliedRuns: kotlin.Long,

    @SerialName(value = "input_rows")
    val inputRows: kotlin.Long,

    @SerialName(value = "candidate_rows")
    val candidateRows: kotlin.Long,

    @SerialName(value = "preserved_rows")
    val preservedRows: kotlin.Long,

    @SerialName(value = "ledger_rows")
    val ledgerRows: kotlin.Long,

    @Contextual @SerialName(value = "latest_import_at")
    val latestImportAt: java.time.OffsetDateTime? = null

) {


}
