/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.HrReadinessSummaryImports

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param imports
 * @param payroll
 * @param annualLeave
 * @param attendance
 */
@Serializable

data class HrReadinessSummary (

    @SerialName(value = "imports")
    val imports: HrReadinessSummaryImports,

    @Contextual @SerialName(value = "payroll")
    val payroll: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @Contextual @SerialName(value = "annual_leave")
    val annualLeave: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @Contextual @SerialName(value = "attendance")
    val attendance: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>

) {


}
