/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A self-service leave-request filing. The subject employee and branch are NOT accepted here — they are resolved from the authenticated caller.
 *
 * @param leaveType 연차 (full-day span) or 반차 (half day, 0.5 on one date).
 * @param startDate YYYY-MM-DD. For a half day the end is forced equal server-side.
 * @param endDate
 * @param reason
 */
@Serializable

data class LeaveCreateRequest (

    /* 연차 (full-day span) or 반차 (half day, 0.5 on one date). */
    @SerialName(value = "leave_type")
    val leaveType: LeaveCreateRequest.LeaveType,

    /* YYYY-MM-DD. For a half day the end is forced equal server-side. */
    @Contextual @SerialName(value = "start_date")
    val startDate: java.time.LocalDate,

    @Contextual @SerialName(value = "end_date")
    val endDate: java.time.LocalDate,

    @SerialName(value = "reason")
    val reason: kotlin.String

) {

    /**
     * 연차 (full-day span) or 반차 (half day, 0.5 on one date).
     *
     * Values: ANNUAL,HALF_DAY
     */
    @Serializable
    enum class LeaveType(val value: kotlin.String) {
        @SerialName(value = "annual") ANNUAL("annual"),
        @SerialName(value = "half_day") HALF_DAY("half_day");
    }

}
