/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A registered edge type (object-link relationship label).
 *
 * @param linkType
 * @param description
 * @param status Edge-type lifecycle state (draft, active, archived).
 */
@Serializable

data class LinkTypeResponse (

    @SerialName(value = "link_type")
    val linkType: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    /* Edge-type lifecycle state (draft, active, archived). */
    @SerialName(value = "status")
    val status: kotlin.String

) {


}
