/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param messageId
 * @param threadId
 * @param acked
 * @param ackCount
 */
@Serializable

data class MessengerAckSummary (

    @Contextual @SerialName(value = "message_id")
    val messageId: java.util.UUID,

    @Contextual @SerialName(value = "thread_id")
    val threadId: java.util.UUID,

    @SerialName(value = "acked")
    val acked: kotlin.Boolean,

    @SerialName(value = "ack_count")
    val ackCount: kotlin.Long

) {


}
