/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.ProductionCapacityIngress
import com.maintenance.api.client.model.ProductionDemandIngress
import com.maintenance.api.client.model.ProductionMaterialIngress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param kind
 * @param id
 * @param inquiryId
 * @param productCode
 * @param quantity
 * @param dueAt
 * @param sourceId
 * @param sourceVersion
 * @param siteId
 * @param capacityDate
 * @param availableQuantity
 * @param materialItemId
 * @param quantityOnHandMilli
 * @param safetyStockMilli
 */
@Serializable

data class ProductionSourceIngress (

    @SerialName(value = "kind")
    val kind: ProductionSourceIngress.Kind,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "inquiry_id")
    val inquiryId: java.util.UUID,

    @SerialName(value = "product_code")
    val productCode: kotlin.String,

    @SerialName(value = "quantity")
    val quantity: kotlin.Long,

    @Contextual @SerialName(value = "due_at")
    val dueAt: java.time.OffsetDateTime,

    @SerialName(value = "source_id")
    val sourceId: kotlin.String,

    @SerialName(value = "source_version")
    val sourceVersion: kotlin.String,

    @Contextual @SerialName(value = "site_id")
    val siteId: java.util.UUID,

    @Contextual @SerialName(value = "capacity_date")
    val capacityDate: java.time.LocalDate,

    @SerialName(value = "available_quantity")
    val availableQuantity: kotlin.Long,

    @Contextual @SerialName(value = "material_item_id")
    val materialItemId: java.util.UUID,

    @SerialName(value = "quantity_on_hand_milli")
    val quantityOnHandMilli: kotlin.Long,

    @SerialName(value = "safety_stock_milli")
    val safetyStockMilli: kotlin.Long

) {

    /**
     *
     *
     * Values: MATERIAL
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "material") MATERIAL("material");
    }

}
