/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param exceptionType
 * @param reason
 * @param attachmentEvidenceId
 * @param escalationApprover
 */
@Serializable

data class PurchaseRequestExceptionInput (

    @SerialName(value = "exception_type")
    val exceptionType: PurchaseRequestExceptionInput.ExceptionType,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @Contextual @SerialName(value = "attachment_evidence_id")
    val attachmentEvidenceId: java.util.UUID? = null,

    @Contextual @SerialName(value = "escalation_approver")
    val escalationApprover: java.util.UUID? = null

) {

    /**
     *
     *
     * Values: PRICE_ANOMALY,MISSING_QUOTE,POLICY_OVERRIDE,BUDGET_OVERRIDE
     */
    @Serializable
    enum class ExceptionType(val value: kotlin.String) {
        @SerialName(value = "PRICE_ANOMALY") PRICE_ANOMALY("PRICE_ANOMALY"),
        @SerialName(value = "MISSING_QUOTE") MISSING_QUOTE("MISSING_QUOTE"),
        @SerialName(value = "POLICY_OVERRIDE") POLICY_OVERRIDE("POLICY_OVERRIDE"),
        @SerialName(value = "BUDGET_OVERRIDE") BUDGET_OVERRIDE("BUDGET_OVERRIDE");
    }

}
