/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param description
 * @param quantity
 * @param unit
 * @param unitPriceWon
 * @param category
 * @param department
 * @param costCenter
 * @param project
 * @param sku
 * @param taxRateBps
 * @param quoteEvidenceId
 * @param neededBy
 */
@Serializable

data class PurchaseRequestLineInput (

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "quantity")
    val quantity: kotlin.Int,

    @SerialName(value = "unit")
    val unit: kotlin.String,

    @SerialName(value = "unit_price_won")
    val unitPriceWon: kotlin.Long,

    @SerialName(value = "category")
    val category: kotlin.String,

    @SerialName(value = "department")
    val department: kotlin.String? = null,

    @SerialName(value = "cost_center")
    val costCenter: kotlin.String? = null,

    @SerialName(value = "project")
    val project: kotlin.String? = null,

    @SerialName(value = "sku")
    val sku: kotlin.String? = null,

    @SerialName(value = "tax_rate_bps")
    val taxRateBps: kotlin.Int? = 0,

    @Contextual @SerialName(value = "quote_evidence_id")
    val quoteEvidenceId: java.util.UUID? = null,

    @Contextual @SerialName(value = "needed_by")
    val neededBy: java.time.LocalDate? = null

) {


}
