/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param exceptionType
 * @param reason
 * @param status
 * @param createdBy
 * @param createdAt
 * @param attachmentEvidenceId
 * @param escalationApprover
 */
@Serializable

data class PurchaseRequestExceptionSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "exception_type")
    val exceptionType: kotlin.String,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "created_by")
    val createdBy: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "attachment_evidence_id")
    val attachmentEvidenceId: java.util.UUID? = null,

    @Contextual @SerialName(value = "escalation_approver")
    val escalationApprover: java.util.UUID? = null

) {


}
