/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param evidenceId
 * @param attachmentType
 * @param preferredQuote
 * @param createdBy
 * @param createdAt
 * @param lineId
 */
@Serializable

data class PurchaseRequestAttachmentSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "evidence_id")
    val evidenceId: java.util.UUID,

    @SerialName(value = "attachment_type")
    val attachmentType: kotlin.String,

    @SerialName(value = "preferred_quote")
    val preferredQuote: kotlin.Boolean,

    @Contextual @SerialName(value = "created_by")
    val createdBy: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "line_id")
    val lineId: java.util.UUID? = null

) {


}
