/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.RaiseAttendanceExceptionRequestEvidenceInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param kind
 * @param employeeId
 * @param workDate
 * @param detail
 * @param branchId
 * @param evidence
 */
@Serializable

data class RaiseAttendanceExceptionRequest (

    @SerialName(value = "kind")
    val kind: kotlin.String,

    @Contextual @SerialName(value = "employee_id")
    val employeeId: java.util.UUID,

    @Contextual @SerialName(value = "work_date")
    val workDate: java.time.LocalDate,

    @SerialName(value = "detail")
    val detail: kotlin.String,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID? = null,

    @SerialName(value = "evidence")
    val evidence: kotlin.collections.List<RaiseAttendanceExceptionRequestEvidenceInner>? = null

) {


}
