/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param branchId
 * @param principalId
 * @param sourceSystem
 * @param credential
 */
@Serializable

data class RegisterProductionSourceSystem (

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "principal_id")
    val principalId: java.util.UUID,

    @SerialName(value = "source_system")
    val sourceSystem: kotlin.String,

    @SerialName(value = "credential")
    val credential: kotlin.String

) {


}
