/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param siteId
 * @param siteName
 * @param customerName
 * @param branchId
 * @param province
 * @param city
 * @param latitude
 * @param longitude
 * @param contactName On-site representative contact name (담당자명).
 * @param contactPhone On-site contact phone (연락처).
 * @param contactEmail Optional contact email (이메일).
 * @param equipmentCount
 * @param rentedCount
 * @param spareCount
 * @param substitutionActiveCount
 */
@Serializable

data class SiteLocationGroup (

    @Contextual @SerialName(value = "site_id")
    val siteId: java.util.UUID,

    @SerialName(value = "site_name")
    val siteName: kotlin.String,

    @SerialName(value = "customer_name")
    val customerName: kotlin.String,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @SerialName(value = "province")
    val province: kotlin.String?,

    @SerialName(value = "city")
    val city: kotlin.String?,

    @SerialName(value = "latitude")
    val latitude: kotlin.Double?,

    @SerialName(value = "longitude")
    val longitude: kotlin.Double?,

    /* On-site representative contact name (담당자명). */
    @SerialName(value = "contact_name")
    val contactName: kotlin.String?,

    /* On-site contact phone (연락처). */
    @SerialName(value = "contact_phone")
    val contactPhone: kotlin.String?,

    /* Optional contact email (이메일). */
    @SerialName(value = "contact_email")
    val contactEmail: kotlin.String?,

    @SerialName(value = "equipment_count")
    val equipmentCount: kotlin.Long,

    @SerialName(value = "rented_count")
    val rentedCount: kotlin.Long,

    @SerialName(value = "spare_count")
    val spareCount: kotlin.Long,

    @SerialName(value = "substitution_active_count")
    val substitutionActiveCount: kotlin.Long

) {


}
