/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Partial site update. Absent keys are left unchanged; nullable keys set to null clear the column. Latitude and longitude must be supplied together and within WGS84 ranges.
 *
 * @param address
 * @param province
 * @param city
 * @param postalCode
 * @param latitude
 * @param longitude
 */
@Serializable

data class UpdateSiteRequest (

    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "province")
    val province: kotlin.String? = null,

    @SerialName(value = "city")
    val city: kotlin.String? = null,

    @SerialName(value = "postal_code")
    val postalCode: kotlin.String? = null,

    @SerialName(value = "latitude")
    val latitude: kotlin.Double? = null,

    @SerialName(value = "longitude")
    val longitude: kotlin.Double? = null

) {


}
