/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param decidable
 * @param reason
 */
@Serializable

data class WorkflowBulkDecisionCapability (

    @SerialName(value = "decidable")
    val decidable: kotlin.Boolean,

    @SerialName(value = "reason")
    val reason: WorkflowBulkDecisionCapability.Reason? = null

) {

    /**
     *
     *
     * Values: NOT_APPROVAL_DECISION_TASK,NOT_OPEN,CLAIMED_BY_ANOTHER_USER,SELF_APPROVAL
     */
    @Serializable
    enum class Reason(val value: kotlin.String) {
        @SerialName(value = "NOT_APPROVAL_DECISION_TASK") NOT_APPROVAL_DECISION_TASK("NOT_APPROVAL_DECISION_TASK"),
        @SerialName(value = "NOT_OPEN") NOT_OPEN("NOT_OPEN"),
        @SerialName(value = "CLAIMED_BY_ANOTHER_USER") CLAIMED_BY_ANOTHER_USER("CLAIMED_BY_ANOTHER_USER"),
        @SerialName(value = "SELF_APPROVAL") SELF_APPROVAL("SELF_APPROVAL");
    }

}
