#!/usr/bin/env python3
"""Generate and validate Buck2 ownership metadata for backend Cargo manifests.

Cargo.toml files are discovery inputs only. Queryable Buck2 labels are the
authority checked by this gate; the generated metadata targets deliberately do
not claim that their Rust crates build under Buck2.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GENERATED_HEADER = (
    "# @generated by tools/buck/backend_manifest_coverage.py; do not edit."
)
DEFAULT_POLICY = Path("backend/ci/gates/buck2-coverage/policy.json")
DEFAULT_REGISTRY = Path(
    "backend/ci/gates/buck2-coverage/ownership.generated.json"
)
REASON_CODE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
BUCK_LABEL = re.compile(r"^//(?P<package>[^:]+):(?P<target>[^:]+)$")


class CoverageError(RuntimeError):
    """Raised when canonical coverage inputs are invalid or unsafe to apply."""


@dataclass(frozen=True)
class Plan:
    entries: tuple[dict[str, str], ...]
    generated_buck: dict[Path, str]
    registry: str

    @property
    def manifest_count(self) -> int:
        return len(self.entries)

    @property
    def exemption_count(self) -> int:
        return sum(entry["disposition"] == "exempt" for entry in self.entries)

    @property
    def owner_count(self) -> int:
        return self.manifest_count - self.exemption_count


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise CoverageError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def _load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_reject_duplicate_keys,
        )
    except FileNotFoundError as error:
        raise CoverageError(f"missing policy file: {path}") from error
    except json.JSONDecodeError as error:
        raise CoverageError(f"invalid JSON in {path}: {error}") from error
    if not isinstance(value, dict):
        raise CoverageError(f"{path} must contain a JSON object")
    return value


def _require_mapping(policy: dict[str, Any], key: str) -> dict[str, Any]:
    value = policy.get(key)
    if not isinstance(value, dict):
        raise CoverageError(f"policy field {key!r} must be an object")
    return value


def _require_reason(manifest: str, value: Any) -> str:
    if not isinstance(value, str) or not value.strip():
        raise CoverageError(f"{manifest} must have a non-empty reason")
    return value.strip()


def _discover_manifests(repo: Path) -> tuple[str, ...]:
    backend = repo / "backend"
    if not backend.is_dir():
        raise CoverageError(f"backend directory is missing under {repo}")
    manifests = tuple(
        sorted(path.relative_to(repo).as_posix() for path in backend.rglob("Cargo.toml"))
    )
    if not manifests:
        raise CoverageError("no backend Cargo.toml manifests discovered")
    return manifests


def _render_generated_buck(target_name: str) -> str:
    return f"""{GENERATED_HEADER}
# Queryable manifest ownership metadata only; this target does not claim Rust build parity.

filegroup(
    name = "{target_name}",
    srcs = ["Cargo.toml"],
    visibility = ["PUBLIC"],
)
"""


def _render_registry(entries: tuple[dict[str, str], ...]) -> str:
    exemption_count = sum(entry["disposition"] == "exempt" for entry in entries)
    registry = {
        "artifact_kind": "BACKEND_CARGO_MANIFEST_BUCK2_OWNERSHIP",
        "schema_version": 1,
        "generated_by": "tools/buck/backend_manifest_coverage.py",
        "authority_boundary": (
            "Cargo manifests are discovery inputs; only queryable Buck2 labels "
            "establish ownership. Generated metadata labels do not assert Rust build parity."
        ),
        "manifest_count": len(entries),
        "queryable_owner_count": len(entries) - exemption_count,
        "exemption_count": exemption_count,
        "entries": list(entries),
    }
    return json.dumps(registry, indent=2, sort_keys=True) + "\n"


def build_plan(repo: Path, policy_path: Path) -> Plan:
    repo = repo.resolve()
    policy_path = policy_path if policy_path.is_absolute() else repo / policy_path
    policy = _load_json(policy_path)
    if policy.get("schema_version") != 1:
        raise CoverageError("policy schema_version must be 1")

    generated_target = policy.get("generated_target_name")
    if not isinstance(generated_target, str) or not REASON_CODE.fullmatch(
        generated_target
    ):
        raise CoverageError(
            "generated_target_name must be a lowercase hyphenated Buck target name"
        )

    exemptions = _require_mapping(policy, "exemptions")
    declared_targets = _require_mapping(policy, "declared_targets")
    overlap = sorted(set(exemptions) & set(declared_targets))
    if overlap:
        raise CoverageError(
            "manifests cannot be both exempt and declared: " + ", ".join(overlap)
        )

    manifests = _discover_manifests(repo)
    discovered = set(manifests)
    policy_paths = set(exemptions) | set(declared_targets)
    stale = sorted(policy_paths - discovered)
    if stale:
        raise CoverageError(
            "policy references undiscovered manifests: " + ", ".join(stale)
        )

    entries: list[dict[str, str]] = []
    generated_buck: dict[Path, str] = {}
    for manifest in manifests:
        package = Path(manifest).parent.as_posix()
        if manifest in exemptions:
            exemption = exemptions[manifest]
            if not isinstance(exemption, dict):
                raise CoverageError(f"exemption for {manifest} must be an object")
            reason_code = exemption.get("reason_code")
            if not isinstance(reason_code, str) or not REASON_CODE.fullmatch(
                reason_code
            ):
                raise CoverageError(
                    f"{manifest} exemption reason_code must be lowercase and hyphenated"
                )
            entries.append(
                {
                    "disposition": "exempt",
                    "manifest": manifest,
                    "reason": _require_reason(manifest, exemption.get("reason")),
                    "reason_code": reason_code,
                }
            )
            continue

        if manifest in declared_targets:
            declaration = declared_targets[manifest]
            if not isinstance(declaration, dict):
                raise CoverageError(f"declared target for {manifest} must be an object")
            label = declaration.get("label")
            match = BUCK_LABEL.fullmatch(label) if isinstance(label, str) else None
            if match is None:
                raise CoverageError(
                    f"{manifest} declared target must be a canonical // label"
                )
            if match.group("package") != package:
                raise CoverageError(
                    f"{label} must be owned by package //{package} for {manifest}"
                )
            entries.append(
                {
                    "disposition": "declared",
                    "label": label,
                    "manifest": manifest,
                    "reason": _require_reason(manifest, declaration.get("reason")),
                }
            )
            continue

        label = f"//{package}:{generated_target}"
        entries.append(
            {
                "disposition": "generated",
                "label": label,
                "manifest": manifest,
            }
        )
        generated_buck[Path(package) / "BUCK"] = _render_generated_buck(
            generated_target
        )

    frozen_entries = tuple(entries)
    return Plan(
        entries=frozen_entries,
        generated_buck=generated_buck,
        registry=_render_registry(frozen_entries),
    )


def _is_generated_buck(path: Path) -> bool:
    try:
        return path.read_text(encoding="utf-8").startswith(GENERATED_HEADER + "\n")
    except (FileNotFoundError, UnicodeDecodeError):
        return False


def _target_is_declared(buck_path: Path, target: str) -> bool:
    try:
        content = buck_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return False
    return re.search(rf'\bname\s*=\s*"{re.escape(target)}"\s*,', content) is not None


def check(repo: Path, policy_path: Path, registry_path: Path) -> list[str]:
    repo = repo.resolve()
    registry_path = registry_path if registry_path.is_absolute() else repo / registry_path
    plan = build_plan(repo, policy_path)
    issues: list[str] = []

    for relative_path, expected in sorted(plan.generated_buck.items()):
        path = repo / relative_path
        if not path.exists():
            issues.append(f"{relative_path.as_posix()} is missing")
        elif path.read_text(encoding="utf-8") != expected:
            if _is_generated_buck(path):
                issues.append(f"{relative_path.as_posix()} generated content drift")
            else:
                issues.append(
                    f"{relative_path.as_posix()} is unmanaged but policy does not "
                    "declare its owner target"
                )

    expected_generated = set(plan.generated_buck)
    for path in sorted((repo / "backend").rglob("BUCK")):
        relative_path = path.relative_to(repo)
        if _is_generated_buck(path) and relative_path not in expected_generated:
            issues.append(f"{relative_path.as_posix()} is stale generated metadata")

    for entry in plan.entries:
        if entry["disposition"] != "declared":
            continue
        match = BUCK_LABEL.fullmatch(entry["label"])
        assert match is not None
        buck_path = repo / match.group("package") / "BUCK"
        if not _target_is_declared(buck_path, match.group("target")):
            issues.append(
                f"{entry['label']} is not declared in "
                f"{buck_path.relative_to(repo).as_posix()}"
            )

    try:
        actual_registry = registry_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        actual_registry = ""
    if actual_registry != plan.registry:
        issues.append(f"{registry_path.name} drift")
    return issues


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def generate(repo: Path, policy_path: Path, registry_path: Path) -> Plan:
    repo = repo.resolve()
    registry_path = registry_path if registry_path.is_absolute() else repo / registry_path
    plan = build_plan(repo, policy_path)

    for relative_path, expected in sorted(plan.generated_buck.items()):
        path = repo / relative_path
        if path.exists() and path.read_text(encoding="utf-8") != expected:
            if not _is_generated_buck(path):
                raise CoverageError(
                    f"refusing to overwrite unmanaged {relative_path.as_posix()}"
                )

    expected_generated = set(plan.generated_buck)
    for path in sorted((repo / "backend").rglob("BUCK")):
        relative_path = path.relative_to(repo)
        if _is_generated_buck(path) and relative_path not in expected_generated:
            path.unlink()

    for relative_path, content in sorted(plan.generated_buck.items()):
        _write_atomic(repo / relative_path, content)
    _write_atomic(registry_path, plan.registry)
    return plan


def _resolve_repo_root(value: str | None) -> Path:
    if value is not None:
        return Path(value).resolve()
    return Path(__file__).resolve().parents[2]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("generate", "check", "labels", "summary"))
    parser.add_argument("--repo-root", help="repository root; defaults from this script")
    parser.add_argument("--policy", default=str(DEFAULT_POLICY))
    parser.add_argument("--registry", default=str(DEFAULT_REGISTRY))
    args = parser.parse_args(argv)

    repo = _resolve_repo_root(args.repo_root)
    policy = Path(args.policy)
    registry = Path(args.registry)
    try:
        if args.command == "generate":
            plan = generate(repo, policy, registry)
            print(
                f"generated {len(plan.generated_buck)} BUCK files for "
                f"{plan.owner_count} queryable owners; {plan.exemption_count} exemption"
            )
            return 0

        plan = build_plan(repo, policy)
        if args.command == "check":
            issues = check(repo, policy, registry)
            if issues:
                for issue in issues:
                    print(f"ERROR: {issue}", file=sys.stderr)
                return 1
            print(
                f"coverage clean: {plan.manifest_count} manifests, "
                f"{plan.owner_count} queryable owners, {plan.exemption_count} exemption"
            )
            return 0
        if args.command == "labels":
            issues = check(repo, policy, registry)
            if issues:
                raise CoverageError(
                    "coverage drift must be repaired before labels are emitted"
                )
            for entry in plan.entries:
                if entry["disposition"] != "exempt":
                    print(entry["label"])
            return 0

        print(
            json.dumps(
                {
                    "exemptions": plan.exemption_count,
                    "generated_buck_files": len(plan.generated_buck),
                    "manifests": plan.manifest_count,
                    "queryable_owners": plan.owner_count,
                },
                sort_keys=True,
            )
        )
        return 0
    except CoverageError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
