#!/usr/bin/env python3
"""Bind every crates.io Cargo.lock identity to the authenticated Buck2 mirror."""

from __future__ import annotations

import argparse
import ast
import hashlib
import os
from pathlib import Path
import re
import stat
import tempfile
import tomllib
import urllib.parse


REPO = Path(__file__).resolve().parents[2]
LOCK = REPO / "backend/Cargo.lock"
BUCK = REPO / "backend/BUCK"
REGISTRY_SOURCE = "registry+https://github.com/rust-lang/crates.io-index"
HEADER = "# @generated by `reindeer buckify`\n"
BOUNDARY_BEGIN = "# BEGIN authenticated current-lock archive boundary"
BOUNDARY_END = "# END authenticated current-lock archive boundary"
LOCK_ONLY_BEGIN = "# BEGIN lock-only archive materialization"
LOCK_ONLY_END = "# END lock-only archive materialization"
ALL_REGISTRY_ARCHIVES_TARGET = "current-lock-registry-archives"
RULE = re.compile(r"(?ms)^http_archive\(\n(.*?)^\)\n")
RUST_LIBRARY_RULE = re.compile(r"(?ms)^cargo\.rust_library\(\n(.*?)^\)\n")
ALIAS_RULE = re.compile(r"(?ms)^alias\(\n(.*?)^\)\n")
LITERAL_INCLUDE_CALL = re.compile(
    r"(?ms)\b(?:include_str|include_bytes)!\s*\((.*?)\)"
)
QUOTED_LITERAL = re.compile(r'^\s*("(?:\\.|[^"\\])*")\s*$')
HEX_64 = re.compile(r"^[0-9a-f]{64}$")
VENDOR_PATCH_TARGETS = {
    "calamine-0.35": (
        "vendor/calamine-0.35.0-quickxml41",
        "//backend/vendor/calamine-0.35.0-quickxml41:calamine-0.35",
    ),
    "quick-xml-0.41": (
        "vendor/quick-xml-0.41.0-compat",
        "//backend/vendor/quick-xml-0.41.0-compat:quick-xml-0.41",
    ),
    "umya-spreadsheet-3": (
        "vendor/umya-spreadsheet-3.0.0-quickxml41",
        "//backend/vendor/umya-spreadsheet-3.0.0-quickxml41:umya-spreadsheet-3",
    ),
}
EXACT_ALIASES = {
    "calamine": VENDOR_PATCH_TARGETS["calamine-0.35"][1],
    "sqlx": ":sqlx-0.9",
    "sqlx-0_8": ":sqlx-0.8",
    "umya-spreadsheet": VENDOR_PATCH_TARGETS["umya-spreadsheet-3"][1],
}


class BindError(RuntimeError):
    pass


def _mirror_route(name: str, version: str) -> str:
    encoded_name = urllib.parse.quote(name, safe="")
    encoded_version = urllib.parse.quote(version, safe="")
    return f"/crates/{encoded_name}/{encoded_version}/download"


def _read_regular(path: Path, purpose: str) -> bytes:
    try:
        metadata = os.lstat(path)
    except FileNotFoundError as error:
        raise BindError(f"missing {purpose}: {path.relative_to(REPO)}") from error
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
        raise BindError(f"{purpose} must be a regular non-symlink: {path.relative_to(REPO)}")
    if not path.resolve(strict=True).is_relative_to(REPO.resolve(strict=True)):
        raise BindError(f"{purpose} escapes repository: {path}")
    return path.read_bytes()


def _vendor_literal_include_resources(manifest_dir: str) -> list[str]:
    """Audit literal include_str/include_bytes inputs of a patched package.

    These path-patched packages have package-owned BUCK rules rather than an
    archive artifact that implicitly carries every package file.  Every Rust
    literal include is therefore discovered from the checked-in package source
    and staged explicitly.  Unsupported/dynamic include expressions fail
    closed rather than silently producing a partial Buck graph.
    """

    package = REPO / "backend" / manifest_dir
    manifest_path = package / "Cargo.toml"
    try:
        manifest = tomllib.loads(_read_regular(manifest_path, "vendor manifest").decode())
    except UnicodeDecodeError as error:
        raise BindError(f"vendor manifest is not UTF-8: {manifest_path.relative_to(REPO)}") from error
    library = manifest.get("lib")
    if not isinstance(library, dict) or not isinstance(library.get("path"), str):
        raise BindError(f"vendor manifest lacks exact [lib].path: {manifest_path.relative_to(REPO)}")
    crate_root = Path(library["path"])
    if crate_root.is_absolute() or ".." in crate_root.parts:
        raise BindError(f"vendor [lib].path must stay in package: {manifest_path.relative_to(REPO)}")
    _read_regular(package / crate_root, "vendor crate root")

    source_root = package / crate_root.parent
    resources: set[str] = set()
    for directory, directory_names, file_names in os.walk(source_root, followlinks=False):
        directory_path = Path(directory)
        for name in tuple(directory_names):
            child = directory_path / name
            metadata = os.lstat(child)
            if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                raise BindError(f"vendor source directory is unsafe: {child.relative_to(REPO)}")
        for name in sorted(file_names):
            if not name.endswith(".rs"):
                continue
            source = directory_path / name
            raw = _read_regular(source, "vendor Rust source")
            try:
                text = raw.decode("utf-8")
            except UnicodeDecodeError as error:
                raise BindError(f"vendor Rust source is not UTF-8: {source.relative_to(REPO)}") from error
            for call in LITERAL_INCLUDE_CALL.finditer(text):
                literal_match = QUOTED_LITERAL.fullmatch(call.group(1))
                if literal_match is None:
                    raise BindError(
                        "vendor include_str/include_bytes expression must be one literal: "
                        f"{source.relative_to(REPO)}"
                    )
                try:
                    literal = ast.literal_eval(literal_match.group(1))
                except (SyntaxError, ValueError) as error:
                    raise BindError(
                        f"invalid vendor include literal: {source.relative_to(REPO)}"
                    ) from error
                if not isinstance(literal, str) or not literal or "\x00" in literal:
                    raise BindError(f"invalid vendor include path: {source.relative_to(REPO)}")
                requested = Path(literal)
                if requested.is_absolute():
                    raise BindError(f"absolute vendor include path: {source.relative_to(REPO)}")
                candidate = source.parent / requested
                raw_resource = _read_regular(candidate, "vendor literal include resource")
                del raw_resource
                resolved = candidate.resolve(strict=True)
                package_root = package.resolve(strict=True)
                if not resolved.is_relative_to(package_root):
                    raise BindError(f"vendor literal include escapes package: {source.relative_to(REPO)}")
                resources.add(resolved.relative_to(package_root).as_posix())
    return sorted(resources)


def _render_vendor_buckfiles() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for _target, (manifest_dir, _label) in sorted(VENDOR_PATCH_TARGETS.items()):
        path = REPO / "backend" / manifest_dir / "BUCK"
        text = _read_regular(path, "vendor BUCK file").decode("utf-8")
        resources = _vendor_literal_include_resources(manifest_dir)
        matches = list(RUST_LIBRARY_RULE.finditer(text))
        if len(matches) != 1:
            raise BindError(f"vendor BUCK must own exactly one Rust library: {path.relative_to(REPO)}")
        rule = matches[0]
        block = rule.group(1)
        srcs = re.search(r"(?ms)^    srcs = \[\n(.*?)^    \],$", block)
        if srcs is None:
            raise BindError(f"vendor Rust library lacks exact srcs list: {path.relative_to(REPO)}")
        entries = re.findall(r'^        "([^"]+)",$', srcs.group(1), re.MULTILINE)
        if len(entries) != len(srcs.group(1).strip().splitlines()):
            raise BindError(f"vendor Rust srcs must be literal package paths: {path.relative_to(REPO)}")
        if len(entries) != len(set(entries)):
            raise BindError(f"vendor Rust srcs contains duplicates: {path.relative_to(REPO)}")
        normalized = sorted(set(entries).union(resources))
        rendered_srcs = "".join(f'        "{entry}",\n' for entry in normalized)
        normalized_block = block[: srcs.start(1)] + rendered_srcs + block[srcs.end(1) :]
        normalized_rule = "cargo.rust_library(\n" + normalized_block + ")\n"
        rendered[path] = text[: rule.start()] + normalized_rule + text[rule.end() :]
    return rendered


def _locked() -> tuple[bytes, list[dict[str, str]]]:
    raw = LOCK.read_bytes()
    document = tomllib.loads(raw.decode())
    if document.get("version") != 4:
        raise BindError("backend/Cargo.lock must use format version 4")
    result: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for package in document.get("package", []):
        source = package.get("source")
        if source is None:
            continue
        name = package.get("name")
        version = package.get("version")
        checksum = package.get("checksum")
        if source != REGISTRY_SOURCE:
            raise BindError(f"unapproved source for {name} {version}: {source!r}")
        if not isinstance(name, str) or not isinstance(version, str):
            raise BindError("registry identity lacks name/version")
        if not isinstance(checksum, str) or HEX_64.fullmatch(checksum) is None:
            raise BindError(f"registry identity lacks exact checksum: {name} {version}")
        identity = (name, version)
        if identity in seen:
            raise BindError(f"duplicate registry identity: {identity}")
        seen.add(identity)
        result.append({"name": name, "version": version, "checksum": checksum})
    return raw, sorted(result, key=lambda item: (item["name"], item["version"]))


def _field(block: str, pattern: str, purpose: str) -> str:
    match = re.search(pattern, block, re.MULTILINE)
    if match is None:
        raise BindError(f"http_archive lacks {purpose}")
    return match.group(1)


def _strip_prior_generated_sections(text: str) -> str:
    for begin, end in (
        (BOUNDARY_BEGIN, BOUNDARY_END),
        (LOCK_ONLY_BEGIN, LOCK_ONLY_END),
    ):
        start = text.find(begin)
        if start < 0:
            continue
        finish = text.find(end, start)
        if finish < 0:
            raise BindError(f"unterminated generated section: {begin}")
        finish += len(end)
        text = text[:start].rstrip("\n") + "\n\n" + text[finish:].lstrip("\n")
    return text


def render() -> str:
    lock_raw, locked = _locked()
    text = BUCK.read_text(encoding="utf-8")
    if not text.startswith(HEADER):
        raise BindError("backend/BUCK lacks Reindeer header")
    text = _strip_prior_generated_sections(text)
    expected = {(item["name"], item["version"]): item for item in locked}
    materialized: set[tuple[str, str]] = set()

    def bind_rule(match: re.Match[str]) -> str:
        block = match.group(1)
        target = _field(block, r'^    name = "([^"]+\.crate)",$', "name")
        checksum = _field(block, r'^    sha256 = "([0-9a-f]+)",$', "checksum")
        strip_prefix = _field(block, r'^    strip_prefix = "([^"]+)",$', "strip prefix")
        candidates = [
            item
            for identity, item in expected.items()
            if strip_prefix == f"{identity[0]}-{identity[1]}"
        ]
        if len(candidates) != 1:
            raise BindError(f"archive {target} resolves to {len(candidates)} lock entries")
        item = candidates[0]
        identity = (item["name"], item["version"])
        if identity in materialized:
            raise BindError(f"duplicate archive identity: {identity}")
        materialized.add(identity)
        if checksum != item["checksum"] or target != f"{strip_prefix}.crate":
            raise BindError(f"archive identity/checksum drift: {target}")
        upstream = (
            f'    urls = ["https://static.crates.io/crates/{item["name"]}/'
            f'{item["version"]}/download"],'
        )
        route = _mirror_route(item["name"], item["version"])
        loopback = f'    urls = [_crate_archive_base_url + "{route}"],'
        legacy_loopback = (
            "    urls = [_crate_archive_base_url + "
            f'"/crates/{item["name"]}/{item["version"]}/download"],'
        )
        if upstream in block:
            block = block.replace(upstream, loopback)
        elif legacy_loopback != loopback and legacy_loopback in block:
            block = block.replace(legacy_loopback, loopback)
        elif loopback not in block:
            raise BindError(f"archive URL is neither exact upstream nor mirror: {target}")
        return "http_archive(\n" + block + ")\n"

    text = RULE.sub(bind_rule, text)

    def own_vendor_patch_once(match: re.Match[str]) -> str:
        block = match.group(1)
        target = _field(block, r'^    name = "([^"]+)",$', "Rust library name")
        vendor = VENDOR_PATCH_TARGETS.get(target)
        if vendor is None:
            return "cargo.rust_library(\n" + block + ")\n"
        manifest_dir, _label = vendor
        exact_manifest = f'        "CARGO_MANIFEST_DIR": "{manifest_dir}",'
        if exact_manifest not in block:
            raise BindError(
                f"Reindeer vendor patch {target} lacks exact manifest ownership"
            )
        return ""

    # Cargo path patches are generated into backend/BUCK by Reindeer, but each
    # checked-in patch has its own package BUCK and one independently validated
    # owner. Remove only the three exact duplicate local rules before aliases
    # are retargeted to those package-owned labels.
    text = RUST_LIBRARY_RULE.sub(own_vendor_patch_once, text)

    def normalize_alias(match: re.Match[str]) -> str:
        block = match.group(1)
        name = _field(block, r'^    name = "([^"]+)",$', "alias name")
        actual = _field(block, r'^    actual = "([^"]+)",$', "alias actual")
        if name == "sqlx" and actual == ":sqlx-0.8":
            block = block.replace('    name = "sqlx",', '    name = "sqlx-0_8",', 1)
        elif name == "calamine" and actual == ":calamine-0.35":
            block = block.replace(
                '    actual = ":calamine-0.35",',
                f'    actual = "{EXACT_ALIASES["calamine"]}",',
                1,
            )
        elif name == "umya-spreadsheet" and actual == ":umya-spreadsheet-3":
            block = block.replace(
                '    actual = ":umya-spreadsheet-3",',
                f'    actual = "{EXACT_ALIASES["umya-spreadsheet"]}",',
                1,
            )
        return "alias(\n" + block + ")\n"

    text = ALIAS_RULE.sub(normalize_alias, text)
    aliases: dict[str, str] = {}
    for block in ALIAS_RULE.findall(text):
        name = _field(block, r'^    name = "([^"]+)",$', "alias name")
        actual = _field(block, r'^    actual = "([^"]+)",$', "alias actual")
        if name in aliases:
            raise BindError(f"duplicate generated alias after normalization: {name}")
        aliases[name] = actual
    for name, actual in EXACT_ALIASES.items():
        if aliases.get(name) != actual:
            raise BindError(
                f"current-lock alias {name} must resolve exactly to {actual}"
            )
    for target, (manifest_dir, _label) in VENDOR_PATCH_TARGETS.items():
        if f'"CARGO_MANIFEST_DIR": "{manifest_dir}"' in text:
            raise BindError(f"vendor patch {target} remains duplicated in backend/BUCK")

    def expose_registry_library(match: re.Match[str]) -> str:
        block = match.group(1)
        private = "    visibility = [],"
        public = '    visibility = ["PUBLIC"],'
        if private in block:
            block = block.replace(private, public, 1)
        elif public not in block:
            target = _field(block, r'^    name = "([^"]+)",$', "name")
            raise BindError(
                f"registry Rust library {target} lacks exact generated visibility"
            )
        return "cargo.rust_library(\n" + block + ")\n"

    # Reindeer aliases are transparent during visibility checking.  Their
    # lock-versioned rust_library targets therefore must themselves be visible
    # to first-party backend packages; a PUBLIC alias over a private actual is
    # not consumable.  This deterministic post-processing is part of the
    # checked-in current-lock graph contract and is independently validated.
    text = RUST_LIBRARY_RULE.sub(expose_registry_library, text)
    lock_sha256 = hashlib.sha256(lock_raw).hexdigest()
    boundary = f'''{BOUNDARY_BEGIN}
load("@toolchains//:config.bzl", "authenticated_crate_archive_base_url")

_crate_archive_base_url = authenticated_crate_archive_base_url("{lock_sha256}")
{BOUNDARY_END}
'''
    insertion = text.find("\n\n", len(HEADER))
    if insertion < 0:
        raise BindError("backend/BUCK has no load section")
    text = text[: insertion + 2] + boundary + "\n" + text[insertion + 2 :]

    missing = [item for item in locked if (item["name"], item["version"]) not in materialized]
    blocks = [LOCK_ONLY_BEGIN]
    for item in missing:
        stem = f'{item["name"]}-{item["version"]}'
        route = _mirror_route(item["name"], item["version"])
        blocks.extend(
            [
                "http_archive(",
                f'    name = "{stem}.crate",',
                f'    sha256 = "{item["checksum"]}",',
                f'    strip_prefix = "{stem}",',
                "    urls = [_crate_archive_base_url + "
                f'"{route}"],',
                "    visibility = [],",
                ")",
                "",
            ]
        )
    blocks.extend(
        [
            "filegroup(",
            f'    name = "{ALL_REGISTRY_ARCHIVES_TARGET}",',
            "    srcs = [",
            *(
                f'        ":{item["name"]}-{item["version"]}.crate",'
                for item in locked
            ),
            "    ],",
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ]
    )
    blocks.append(LOCK_ONLY_END)
    return text.rstrip() + "\n\n" + "\n".join(blocks) + "\n"


def _write_atomic(path: Path, content: str) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        expected = render()
        expected_vendor = _render_vendor_buckfiles()
        if args.write:
            _write_atomic(BUCK, expected)
            for path, content in expected_vendor.items():
                _write_atomic(path, content)
            print(
                "bound every Cargo.lock registry archive and vendor literal include "
                "resource to authenticated Buck2 inputs"
            )
        elif BUCK.read_text(encoding="utf-8") != expected:
            raise BindError("backend/BUCK offline archive binding is stale")
        elif any(path.read_text(encoding="utf-8") != content for path, content in expected_vendor.items()):
            raise BindError("vendor literal include resource binding is stale")
        else:
            print("backend/BUCK archive and vendor literal include bindings exact")
    except (BindError, OSError, tomllib.TOMLDecodeError) as error:
        print(f"bind-current-lock-archives: {error}", file=os.sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
