#!/usr/bin/env python3
"""Validate and attest the checked-in current-lock Buck2 Rust graph.

Reindeer emits ``backend/BUCK`` from the locked backend workspace.  This
validator independently binds every downloadable archive to Cargo.lock,
rejects unknown sources/checksum ambiguity, resolves every local lock package
to one contained Cargo manifest, and writes a deterministic graph receipt.
Cargo is not invoked here and is not part of build or verification authority.
"""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile
import tomllib
import urllib.parse
from typing import Any


REGISTRY_SOURCE = "registry+https://github.com/rust-lang/crates.io-index"
REINDEER_COMMIT = "681727ced54a853977ac495e147ac54e1c0db115"
LOCK_PATH = Path("backend/Cargo.lock")
BUCK_PATH = Path("backend/BUCK")
RECEIPT_PATH = Path("backend/current-lock-rust-graph.generated.json")
TOOLCHAIN_LOCK_PATH = Path("tools/buck/toolchain-lock.json")
TOOLCHAIN_BUCK_PATH = Path("toolchains/BUCK")
TOOLCHAIN_CONFIG_PATH = Path("toolchains/config.bzl")
OPENSSL_SYS_FIXUP_PATH = Path("backend/fixups/openssl-sys/fixups.toml")
OPENSSL_FIXUP_PATH = Path("backend/fixups/openssl/fixups.toml")
SQLX_MIGRATIONS_PATH = Path("backend/crates/platform/db/migrations")
SQLX_MIGRATION_HELPER_PATH = Path(
    "backend/crates/platform/db/sqlx_migration_sources.bzl"
)
SQLX_MIGRATION_IDENTITY_SOURCE_PATH = Path(
    "backend/crates/platform/db/buck2_contract_tests/"
    "canonical_migration_identities.generated.rs"
)
SQLX_MIGRATION_SENTINEL_SOURCE_PATH = Path(
    "backend/crates/platform/db/buck2_contract_tests/period_lock_domain.rs"
)
SQLX_MIGRATION_PLATFORM_DB_BUCK_PATH = Path("backend/crates/platform/db/BUCK")
SQLX_MIGRATION_CONSUMERS = {
    Path("backend/app/BUCK"): 2,
    Path("backend/crates/finance-gl/adapter-postgres/BUCK"): 1,
    Path("backend/crates/platform/db/BUCK"): 1,
}
GENERATED_HEADER = "# @generated by `reindeer buckify`"
MIRROR_LOAD = 'load("@toolchains//:config.bzl", "authenticated_crate_archive_base_url")'
ALL_REGISTRY_ARCHIVES_TARGET = "current-lock-registry-archives"
EXACT_CURRENT_LOCK_ALIASES = {
    "calamine": "//backend/vendor/calamine-0.35.0-quickxml41:calamine-0.35",
    "sqlx": ":sqlx-0.9",
    "sqlx-0_8": ":sqlx-0.8",
    "umya-spreadsheet": (
        "//backend/vendor/umya-spreadsheet-3.0.0-quickxml41:umya-spreadsheet-3"
    ),
}
VENDOR_PATCH_MANIFEST_DIRS = {
    "vendor/calamine-0.35.0-quickxml41",
    "vendor/quick-xml-0.41.0-compat",
    "vendor/umya-spreadsheet-3.0.0-quickxml41",
}
HEX_64 = re.compile(r"^[0-9a-f]{64}$")
SQLX_MIGRATION_FILENAME = re.compile(r"^(\d{4})_([a-z0-9_]+)\.sql$")
TOP_LEVEL_RULE = re.compile(r"(?ms)^([A-Za-z0-9_.]+)\(\n(.*?)^\)\n")
LITERAL_INCLUDE_CALL = re.compile(
    r"(?ms)\b(?:include_str|include_bytes)!\s*\((.*?)\)"
)
QUOTED_LITERAL = re.compile(r'^\s*("(?:\\.|[^"\\])*")\s*$')
REQUIRED_BUILDSCRIPT_PACKAGES = {
    "cedar-policy-core": {
        "library_target": "cedar-policy-core-4",
        "required_build_deps": ("lalrpop-0.22",),
    }
}
OPENSSL_SYS_CFGS = (
    "openssl",
    "ossl101",
    "ossl102",
    "ossl102f",
    "ossl102h",
    "ossl110",
    "ossl110f",
    "ossl110g",
    "ossl110h",
    "ossl111",
    "ossl111b",
    "ossl111c",
    "ossl111d",
    "ossl300",
    "ossl320",
    "ossl330",
    "ossl340",
    "ossl350",
    'osslconf="OPENSSL_NO_SSL3_METHOD"',
)
OPENSSL_CFGS = (
    "ossl101",
    "ossl102",
    "ossl110",
    "ossl110g",
    "ossl110h",
    "ossl111",
    "ossl111d",
    "ossl300",
    "ossl310",
    "ossl320",
    "ossl330",
    "ossl340",
    "ossl350",
)


class GraphError(RuntimeError):
    """The checked-in graph is not an exact, safe projection of the lock."""


@dataclass(frozen=True)
class LockedPackage:
    name: str
    version: str
    source: str | None
    checksum: str | None

    @property
    def key(self) -> tuple[str, str, str]:
        return (self.name, self.version, self.source or "path")


def _repo_root() -> Path:
    configured = os.environ.get("MAINTENANCE_REPO_ROOT")
    if configured:
        root = Path(configured)
        if not root.is_absolute() or not (root / ".buckroot").is_file():
            raise GraphError("MAINTENANCE_REPO_ROOT is not the Buck2 project root")
        return root.resolve(strict=True)
    return Path(__file__).resolve().parents[2]


def _read_regular(repo: Path, relative: Path) -> bytes:
    path = repo / relative
    try:
        metadata = os.lstat(path)
    except FileNotFoundError as error:
        raise GraphError(f"required file is missing: {relative.as_posix()}") from error
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
        raise GraphError(f"required file must be a regular non-symlink: {relative.as_posix()}")
    if path.resolve(strict=True).is_relative_to(repo) is False:
        raise GraphError(f"required file escapes repository: {relative.as_posix()}")
    return path.read_bytes()


def _render_sqlx_migration_identity_source(
    migrations: list[dict[str, Any]],
) -> str:
    lines = [
        "// @generated by tools/buck/current_lock_rust_graph.py; do not edit.",
        "pub const CANONICAL_SQLX_MIGRATION_IDENTITIES: &[(&str, &str)] = &[",
    ]
    lines.extend(
        f'    ("{migration["path"]}", "{migration["sha256"]}"),'
        for migration in migrations
    )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def _canonical_sqlx_migration_contract(
    repo: Path,
) -> tuple[list[dict[str, Any]], dict[str, Any], str]:
    directory = repo / SQLX_MIGRATIONS_PATH
    try:
        directory_metadata = os.lstat(directory)
    except FileNotFoundError as error:
        raise GraphError(
            f"canonical SQLx migration directory is missing: {SQLX_MIGRATIONS_PATH}"
        ) from error
    if stat.S_ISLNK(directory_metadata.st_mode) or not stat.S_ISDIR(
        directory_metadata.st_mode
    ):
        raise GraphError("canonical SQLx migration directory must be a real directory")
    if not directory.resolve(strict=True).is_relative_to(repo):
        raise GraphError("canonical SQLx migration directory escapes repository")

    entries = sorted(directory.iterdir(), key=lambda path: path.name)
    migrations: list[dict[str, Any]] = []
    for entry in entries:
        relative = entry.relative_to(repo)
        match = SQLX_MIGRATION_FILENAME.fullmatch(entry.name)
        if match is None:
            raise GraphError(
                f"invalid canonical SQLx migration member: {relative.as_posix()}"
            )
        raw = _read_regular(repo, relative)
        migrations.append(
            {
                "path": relative.as_posix(),
                "sha256": hashlib.sha256(raw).hexdigest(),
                "size": len(raw),
                "version": int(match.group(1)),
            }
        )
    expected_versions = list(range(1, 169))
    actual_versions = [migration["version"] for migration in migrations]
    if actual_versions != expected_versions:
        raise GraphError(
            "canonical SQLx migration versions must be exactly contiguous 0001..0168"
        )
    if migrations[0]["path"] != (
        SQLX_MIGRATIONS_PATH / "0001_create_regions_branches.sql"
    ).as_posix():
        raise GraphError("canonical SQLx migration 0001 identity is not exact")
    if migrations[25]["path"] != (
        SQLX_MIGRATIONS_PATH / "0026_create_organizations.sql"
    ).as_posix():
        raise GraphError("canonical SQLx migration 0026 identity is not exact")
    if migrations[-1]["path"] != (
        SQLX_MIGRATIONS_PATH / "0168_runtime_public_schema_usage.sql"
    ).as_posix():
        raise GraphError("canonical SQLx migration 0168 identity is not exact")
    if re.search(
        rb"(?im)^CREATE TABLE regions\s*\(",
        _read_regular(repo, Path(migrations[0]["path"])),
    ) is None:
        raise GraphError("canonical SQLx migration 0001 must create regions")
    if re.search(
        rb"(?im)^CREATE TABLE organizations\s*\(",
        _read_regular(repo, Path(migrations[25]["path"])),
    ) is None:
        raise GraphError("canonical SQLx migration 0026 must create organizations")

    helper_raw = _read_regular(repo, SQLX_MIGRATION_HELPER_PATH)
    try:
        helper = helper_raw.decode("utf-8")
    except UnicodeDecodeError as error:
        raise GraphError("canonical SQLx migration helper is not UTF-8") from error
    helper_fragments = (
        '_CANONICAL_SQLX_MIGRATION_TARGET = "//backend/crates/platform/db:sqlx-migrations"',
        '_CANONICAL_SQLX_MIGRATION_DESTINATION = "backend/crates/platform/db"',
        "def with_canonical_sqlx_migrations(mapped_srcs):",
        "result = dict(mapped_srcs)",
        "if _CANONICAL_SQLX_MIGRATION_TARGET in result:",
        'fail("canonical SQLx migrations must be added only by this helper")',
        "result[_CANONICAL_SQLX_MIGRATION_TARGET] = _CANONICAL_SQLX_MIGRATION_DESTINATION",
    )
    if any(helper.count(fragment) != 1 for fragment in helper_fragments):
        raise GraphError("canonical SQLx migration helper path transform is not exact")
    if '"backend/crates/platform/db/migrations"' in helper:
        raise GraphError("canonical SQLx migration helper creates double nesting")

    load = (
        'load("//backend/crates/platform/db:sqlx_migration_sources.bzl", '
        '"with_canonical_sqlx_migrations")'
    )
    consumers: list[dict[str, Any]] = []
    forbidden_direct_map = (
        '"//backend/crates/platform/db:sqlx-migrations": '
        '"backend/crates/platform/db/migrations"'
    )
    for path, expected_calls in SQLX_MIGRATION_CONSUMERS.items():
        raw = _read_regular(repo, path)
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError as error:
            raise GraphError(
                f"canonical SQLx migration consumer is not UTF-8: {path}"
            ) from error
        if text.count(load) != 1 or text.count(
            "mapped_srcs = with_canonical_sqlx_migrations({"
        ) != expected_calls:
            raise GraphError(
                f"canonical SQLx migration consumer does not use one staging primitive: {path}"
            )
        if forbidden_direct_map in text:
            raise GraphError(
                f"canonical SQLx migration consumer creates double nesting: {path}"
            )
        consumers.append(
            {
                "helper_call_count": expected_calls,
                "path": path.as_posix(),
                "sha256": hashlib.sha256(raw).hexdigest(),
            }
        )

    platform_db_buck = _read_regular(repo, SQLX_MIGRATION_PLATFORM_DB_BUCK_PATH).decode(
        "utf-8"
    )
    disjoint_contract_source_mappings = (
        '"buck2_contract_tests/canonical_migration_identities.generated.rs": '
        '"backend/buck2_contract_tests/platform_db/'
        'canonical_migration_identities.generated.rs"',
        '"buck2_contract_tests/period_lock_domain.rs": '
        '"backend/buck2_contract_tests/platform_db/period_lock_domain.rs"',
    )
    if any(
        platform_db_buck.count(mapping) != 1
        for mapping in disjoint_contract_source_mappings
    ) or '"backend/crates/platform/db/buck2_contract_tests/' in platform_db_buck:
        raise GraphError(
            "canonical SQLx migration platform DB contract sources must remain disjoint "
            "from migration staging"
        )

    sentinel_raw = _read_regular(repo, SQLX_MIGRATION_SENTINEL_SOURCE_PATH)
    try:
        sentinel_source = sentinel_raw.decode("utf-8")
    except UnicodeDecodeError as error:
        raise GraphError("canonical SQLx migration sentinel is not UTF-8") from error
    if (
        sentinel_source.count('sqlx::migrate!("./migrations")') != 1
        or 'sqlx::migrate!("migrations")' in sentinel_source
    ):
        raise GraphError(
            "canonical SQLx migration sentinel must use exact manifest-relative "
            'migrate!("./migrations") semantics'
        )

    identity_source = _render_sqlx_migration_identity_source(migrations)
    staging = {
        "consumer_buckfiles": consumers,
        "destination": "backend/crates/platform/db",
        "helper": {
            "path": SQLX_MIGRATION_HELPER_PATH.as_posix(),
            "sha256": hashlib.sha256(helper_raw).hexdigest(),
        },
        "runtime_sentinel": {
            "migration_literal": "./migrations",
            "path": SQLX_MIGRATION_SENTINEL_SOURCE_PATH.as_posix(),
            "sha256": hashlib.sha256(sentinel_raw).hexdigest(),
        },
        "source_target": "//backend/crates/platform/db:sqlx-migrations",
    }
    return migrations, staging, identity_source


def _load_lock(repo: Path) -> tuple[bytes, list[LockedPackage]]:
    raw = _read_regular(repo, LOCK_PATH)
    try:
        document = tomllib.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
        raise GraphError(f"invalid {LOCK_PATH.as_posix()}: {error}") from error
    if document.get("version") != 4:
        raise GraphError("backend/Cargo.lock must remain lock format version 4")
    packages: list[LockedPackage] = []
    seen: set[tuple[str, str, str]] = set()
    for value in document.get("package", []):
        if not isinstance(value, dict):
            raise GraphError("Cargo.lock package entries must be tables")
        name = value.get("name")
        version = value.get("version")
        source = value.get("source")
        checksum = value.get("checksum")
        if not isinstance(name, str) or not name:
            raise GraphError("Cargo.lock package has invalid name")
        if not isinstance(version, str) or not version:
            raise GraphError(f"Cargo.lock package {name} has invalid version")
        if source is not None and source != REGISTRY_SOURCE:
            raise GraphError(f"unrecognized locked source for {name} {version}: {source!r}")
        if source == REGISTRY_SOURCE:
            if not isinstance(checksum, str) or HEX_64.fullmatch(checksum) is None:
                raise GraphError(f"registry package {name} {version} lacks exact SHA-256")
        elif checksum is not None:
            raise GraphError(f"local package {name} {version} must not carry registry checksum")
        package = LockedPackage(name, version, source, checksum)
        if package.key in seen:
            raise GraphError(f"duplicate locked package identity: {package.key}")
        seen.add(package.key)
        packages.append(package)
    if not packages:
        raise GraphError("Cargo.lock contains no packages")
    return raw, sorted(packages, key=lambda package: package.key)


def _package_version(package: dict[str, Any], workspace_package: dict[str, Any]) -> str:
    value = package.get("version")
    if isinstance(value, str):
        return value
    if isinstance(value, dict) and value.get("workspace") is True:
        inherited = workspace_package.get("version")
        if isinstance(inherited, str):
            return inherited
        raise GraphError("package inherits workspace version but workspace has none")
    if value is None:
        return "0.0.0"
    raise GraphError("package version must be a string, workspace inheritance, or omitted")


def _discover_local_manifests(
    repo: Path, local_lock: list[LockedPackage]
) -> list[dict[str, str]]:
    backend = repo / "backend"
    workspace = tomllib.loads(_read_regular(repo, Path("backend/Cargo.toml")).decode("utf-8"))
    workspace_package = workspace.get("workspace", {}).get("package", {})
    discovered: dict[tuple[str, str], list[str]] = {}
    for directory, directory_names, file_names in os.walk(backend, followlinks=False):
        directory_path = Path(directory)
        for name in tuple(directory_names):
            child = directory_path / name
            metadata = os.lstat(child)
            if stat.S_ISLNK(metadata.st_mode):
                raise GraphError(f"local manifest discovery rejects symlink directory: {child}")
            if not stat.S_ISDIR(metadata.st_mode):
                raise GraphError(f"local manifest discovery found non-directory: {child}")
        if "Cargo.toml" not in file_names or directory_path == backend:
            continue
        manifest = directory_path / "Cargo.toml"
        metadata = os.lstat(manifest)
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise GraphError(f"local manifest must be a regular non-symlink: {manifest}")
        try:
            document = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
            raise GraphError(f"invalid local manifest {manifest}: {error}") from error
        package = document.get("package")
        if not isinstance(package, dict):
            continue
        name = package.get("name")
        if not isinstance(name, str) or not name:
            raise GraphError(f"local manifest has invalid package name: {manifest}")
        version = _package_version(package, workspace_package)
        relative = manifest.relative_to(repo).as_posix()
        discovered.setdefault((name, version), []).append(relative)

    local_keys = {(package.name, package.version) for package in local_lock}
    if len(local_keys) != len(local_lock):
        raise GraphError("local lock identities are ambiguous without a source discriminator")
    extra = sorted(set(discovered) - local_keys)
    if extra:
        raise GraphError(f"local manifests absent from Cargo.lock: {extra}")
    result: list[dict[str, str]] = []
    for package in local_lock:
        paths = discovered.get((package.name, package.version), [])
        if len(paths) != 1:
            raise GraphError(
                f"local package {package.name} {package.version} resolves to {len(paths)} manifests: {paths}"
            )
        manifest = paths[0]
        kind = "vendor-patch" if manifest.startswith("backend/vendor/") else "workspace"
        result.append(
            {
                "kind": kind,
                "manifest": manifest,
                "name": package.name,
                "version": package.version,
            }
        )
    return sorted(result, key=lambda item: (item["name"], item["version"], item["manifest"]))


def _vendor_literal_include_resources(
    repo: Path, package: dict[str, str]
) -> list[dict[str, str]]:
    package_path = Path(package["manifest"]).parent
    package_root = repo / package_path
    manifest = tomllib.loads(_read_regular(repo, Path(package["manifest"])).decode("utf-8"))
    library = manifest.get("lib")
    if not isinstance(library, dict) or not isinstance(library.get("path"), str):
        raise GraphError(f"vendor manifest lacks exact [lib].path: {package['manifest']}")
    crate_root = Path(library["path"])
    if crate_root.is_absolute() or ".." in crate_root.parts:
        raise GraphError(f"vendor [lib].path escapes package: {package['manifest']}")
    _read_regular(repo, package_path / crate_root)

    source_root = package_root / crate_root.parent
    resources: set[Path] = set()
    for directory, directory_names, file_names in os.walk(source_root, followlinks=False):
        directory_path = Path(directory)
        for name in tuple(directory_names):
            child = directory_path / name
            metadata = os.lstat(child)
            if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                raise GraphError(f"vendor source directory is unsafe: {child}")
        for name in sorted(file_names):
            if not name.endswith(".rs"):
                continue
            source = directory_path / name
            source_relative = source.relative_to(repo)
            try:
                text = _read_regular(repo, source_relative).decode("utf-8")
            except UnicodeDecodeError as error:
                raise GraphError(
                    f"vendor Rust source is not UTF-8: {source_relative.as_posix()}"
                ) from error
            for call in LITERAL_INCLUDE_CALL.finditer(text):
                literal_match = QUOTED_LITERAL.fullmatch(call.group(1))
                if literal_match is None:
                    raise GraphError(
                        "vendor include_str/include_bytes expression must be one literal: "
                        f"{source_relative.as_posix()}"
                    )
                try:
                    literal = ast.literal_eval(literal_match.group(1))
                except (SyntaxError, ValueError) as error:
                    raise GraphError(
                        f"invalid vendor include literal: {source_relative.as_posix()}"
                    ) from error
                if not isinstance(literal, str) or not literal or "\x00" in literal:
                    raise GraphError(
                        f"invalid vendor include path: {source_relative.as_posix()}"
                    )
                requested = Path(literal)
                if requested.is_absolute():
                    raise GraphError(
                        f"absolute vendor include path: {source_relative.as_posix()}"
                    )
                candidate = source.parent / requested
                try:
                    resolved = candidate.resolve(strict=True)
                except FileNotFoundError as error:
                    raise GraphError(
                        f"vendor literal include resource is missing: {source_relative.as_posix()}"
                    ) from error
                if not resolved.is_relative_to(package_root.resolve(strict=True)):
                    raise GraphError(
                        f"vendor literal include escapes package: {source_relative.as_posix()}"
                    )
                relative = resolved.relative_to(repo)
                _read_regular(repo, relative)
                resources.add(relative)
    return [
        {
            "path": (repo / resource).relative_to(package_root).as_posix(),
            "sha256": hashlib.sha256(_read_regular(repo, resource)).hexdigest(),
        }
        for resource in sorted(resources)
    ]


def _field(block: str, pattern: str, purpose: str) -> str:
    match = re.search(pattern, block, re.MULTILINE)
    if match is None:
        raise GraphError(f"generated Buck rule lacks {purpose}")
    return match.group(1)


def _literal_string_list(block: str, field: str, purpose: str) -> tuple[str, ...]:
    match = re.search(
        rf"(?ms)^    {re.escape(field)} = \[\n(.*?)^    \],$", block
    )
    if match is None:
        raise GraphError(f"generated Buck rule lacks exact {purpose}")
    values: list[str] = []
    consumed: list[str] = []
    for line in match.group(1).splitlines():
        literal = re.fullmatch(r'        ("(?:\\.|[^"\\])*")[,]?', line)
        if literal is None:
            raise GraphError(f"generated Buck rule has non-literal {purpose}")
        try:
            value = ast.literal_eval(literal.group(1))
        except (SyntaxError, ValueError) as error:
            raise GraphError(f"generated Buck rule has invalid {purpose}") from error
        if not isinstance(value, str):
            raise GraphError(f"generated Buck rule has non-string {purpose}")
        values.append(value)
        consumed.append(line)
    if not consumed:
        raise GraphError(f"generated Buck rule has empty {purpose}")
    return tuple(values)


def _load_json_object(repo: Path, relative: Path) -> tuple[bytes, dict[str, Any]]:
    raw = _read_regular(repo, relative)

    def reject_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise GraphError(f"duplicate JSON key in {relative.as_posix()}: {key}")
            result[key] = value
        return result

    try:
        document = json.loads(raw, object_pairs_hook=reject_duplicates)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise GraphError(f"invalid {relative.as_posix()}: {error}") from error
    if not isinstance(document, dict):
        raise GraphError(f"{relative.as_posix()} must contain one JSON object")
    return raw, document


def _validate_openssl_native_contract(
    repo: Path,
    rules_by_name: dict[str, tuple[str, str]],
    registry_lock: list[LockedPackage],
) -> dict[str, Any]:
    locked_versions: dict[str, str] = {}
    for package_name in ("openssl-sys", "openssl"):
        locked = [
            package for package in registry_lock if package.name == package_name
        ]
        if len(locked) != 1:
            raise GraphError(
                f"required OpenSSL package {package_name} resolves to {len(locked)} lock entries"
            )
        locked_versions[package_name] = locked[0].version
    if locked_versions != {"openssl-sys": "0.9.116", "openssl": "0.10.80"}:
        raise GraphError(
            f"OpenSSL cfg contract is stale for locked packages: {locked_versions}"
        )

    generated_contracts = {
        "openssl-sys-0.9": OPENSSL_SYS_CFGS,
        "openssl-0.10": OPENSSL_CFGS,
    }
    for target, expected_cfgs in generated_contracts.items():
        rule = rules_by_name.get(target)
        if rule is None or rule[0] != "cargo.rust_library":
            raise GraphError(f"required OpenSSL target {target} is missing")
        actual_cfgs = tuple(
            flag.removeprefix("--cfg=")
            for flag in _literal_string_list(
                rule[1], "rustc_flags", f"OpenSSL cfgs for {target}"
            )
            if flag.startswith("--cfg=")
        )
        if actual_cfgs != expected_cfgs:
            raise GraphError(f"OpenSSL cfg contract is not exact for {target}")
        if "build-script" in rule[1] or "rustc-link" in rule[1]:
            raise GraphError(f"OpenSSL target {target} contains ambient build output")
    openssl_sys_block = rules_by_name["openssl-sys-0.9"][1]
    native_label = "toolchains//:openssl-static"
    if openssl_sys_block.count(f'        "{native_label}",') != 1:
        raise GraphError(
            "OpenSSL native dependency must reference toolchains//:openssl-static exactly once"
        )
    if any(
        target.startswith(("openssl-sys-0.9-build-script", "openssl-0.10-build-script"))
        for target in rules_by_name
    ):
        raise GraphError("OpenSSL buildscript host discovery must remain disabled")

    fixup_contracts = {
        OPENSSL_SYS_FIXUP_PATH: {
            "cfgs": list(OPENSSL_SYS_CFGS),
            "extra_deps": [native_label],
        },
        OPENSSL_FIXUP_PATH: {"cfgs": list(OPENSSL_CFGS)},
    }
    contract_files: list[dict[str, str]] = []
    for path, expected in fixup_contracts.items():
        raw = _read_regular(repo, path)
        try:
            document = tomllib.loads(raw.decode("utf-8"))
        except (UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
            raise GraphError(f"invalid OpenSSL fixup {path.as_posix()}: {error}") from error
        if document.get("buildscript") != {"run": False}:
            raise GraphError(
                f"OpenSSL fixup {path.as_posix()} must disable host discovery"
            )
        for key, value in expected.items():
            if document.get(key) != value:
                raise GraphError(
                    f"OpenSSL fixup {path.as_posix()} has non-exact {key}"
                )
        contract_files.append(
            {"path": path.as_posix(), "sha256": hashlib.sha256(raw).hexdigest()}
        )

    toolchain_lock_raw, toolchain_lock = _load_json_object(
        repo, TOOLCHAIN_LOCK_PATH
    )
    expected_platforms = {
        "macos-aarch64",
        "macos-x86_64",
        "linux-aarch64",
        "linux-x86_64",
    }
    platforms = toolchain_lock.get("platforms")
    if not isinstance(platforms, dict) or set(platforms) != expected_platforms:
        raise GraphError("OpenSSL toolchain lock platform matrix is incomplete")
    platform_receipts: list[dict[str, Any]] = []
    bottle_digests: set[str] = set()
    for platform_name in sorted(expected_platforms):
        platform_entry = platforms[platform_name]
        openssl = platform_entry.get("openssl") if isinstance(platform_entry, dict) else None
        if not isinstance(openssl, dict) or openssl.get("version") != "3.6.3":
            raise GraphError(f"OpenSSL toolchain version is invalid for {platform_name}")
        bottle_sha = openssl.get("sha256")
        bottle_size = openssl.get("size")
        if (
            not isinstance(bottle_sha, str)
            or HEX_64.fullmatch(bottle_sha) is None
            or type(bottle_size) is not int
            or bottle_size <= 0
            or openssl.get("url")
            != "https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:"
            + bottle_sha
            or openssl.get("filename")
            != f"openssl-3.6.3-{platform_name}.bottle.tar.gz"
        ):
            raise GraphError(f"OpenSSL bottle identity is invalid for {platform_name}")
        bottle_digests.add(bottle_sha)
        libraries = openssl.get("static_libraries")
        if not isinstance(libraries, dict) or set(libraries) != {"ssl", "crypto"}:
            raise GraphError(
                f"OpenSSL static library matrix is incomplete for {platform_name}"
            )
        library_receipts: dict[str, dict[str, Any]] = {}
        for library_name in ("ssl", "crypto"):
            identity = libraries[library_name]
            filename = f"lib{library_name}.a"
            if (
                not isinstance(identity, dict)
                or identity.get("filename") != filename
                or identity.get("archive_path")
                != f"openssl@3/3.6.3/lib/{filename}"
                or not isinstance(identity.get("sha256"), str)
                or HEX_64.fullmatch(identity["sha256"]) is None
                or identity["sha256"] == "0" * 64
                or type(identity.get("size")) is not int
                or identity["size"] <= 0
            ):
                raise GraphError(
                    f"OpenSSL static library {library_name} identity is invalid for {platform_name}"
                )
            library_receipts[library_name] = {
                "archive_path": identity["archive_path"],
                "filename": filename,
                "sha256": identity["sha256"],
                "size": identity["size"],
            }
        platform_receipts.append(
            {
                "bottle_sha256": bottle_sha,
                "bottle_size": bottle_size,
                "platform": platform_name,
                "static_libraries": library_receipts,
            }
        )
    if len(bottle_digests) != len(expected_platforms):
        raise GraphError("OpenSSL platform bottles must have distinct identities")

    toolchain_buck_raw = _read_regular(repo, TOOLCHAIN_BUCK_PATH)
    config_raw = _read_regular(repo, TOOLCHAIN_CONFIG_PATH)
    try:
        toolchain_buck = toolchain_buck_raw.decode("utf-8")
        config = config_raw.decode("utf-8")
    except UnicodeDecodeError as error:
        raise GraphError("OpenSSL toolchain contract is not UTF-8") from error
    if config.count("def authenticated_loopback_artifact_url(") != 1:
        raise GraphError("OpenSSL toolchain lacks one exact loopback URL validator")
    toolchain_rules = {
        _field(block, r'^    name = "([^"]+)",$', "toolchain rule name"): (
            kind,
            block,
        )
        for kind, block in TOP_LEVEL_RULE.findall(toolchain_buck)
    }
    for library_name in ("ssl", "crypto"):
        target = f"openssl-lib{library_name}-static"
        rule = toolchain_rules.get(target)
        if rule is None or rule[0] != "native.http_file":
            raise GraphError(f"OpenSSL toolchain target {target} must be native.http_file")
        for fragment in (
            f"    urls = [_openssl_{library_name}_url],",
            f"    sha256 = _openssl_{library_name}_sha256,",
            f"    size_bytes = int(_openssl_{library_name}_size),",
            f'    out = "lib{library_name}.a",',
            "    visibility = [],",
        ):
            if rule[1].count(fragment) != 1:
                raise GraphError(f"OpenSSL toolchain target {target} is not exact")
    group = toolchain_rules.get("openssl-static")
    if group is None or group[0] != "native.prebuilt_cxx_library_group":
        raise GraphError("OpenSSL native dependency group is missing")
    for fragment in (
        '    static_libs = [":openssl-libssl-static", ":openssl-libcrypto-static"],',
        '    static_link = ["$(lib 0)", "$(lib 1)"],',
        '    static_pic_libs = [":openssl-libssl-static", ":openssl-libcrypto-static"],',
        '    static_pic_link = ["$(lib 0)", "$(lib 1)"],',
        '    visibility = ["PUBLIC"],',
    ):
        if group[1].count(fragment) != 1:
            raise GraphError("OpenSSL native dependency group is not exact")
    forbidden = (".buckconfig.local", "/opt/homebrew", "/usr/local", "rustc_link_lib")
    if any(value in toolchain_buck + config for value in forbidden):
        raise GraphError("OpenSSL toolchain contract contains ambient host linkage")

    contract_files.extend(
        [
            {
                "path": TOOLCHAIN_LOCK_PATH.as_posix(),
                "sha256": hashlib.sha256(toolchain_lock_raw).hexdigest(),
            },
            {
                "path": TOOLCHAIN_BUCK_PATH.as_posix(),
                "sha256": hashlib.sha256(toolchain_buck_raw).hexdigest(),
            },
            {
                "path": TOOLCHAIN_CONFIG_PATH.as_posix(),
                "sha256": hashlib.sha256(config_raw).hexdigest(),
            },
        ]
    )
    return {
        "contract_files": sorted(contract_files, key=lambda item: item["path"]),
        "generated_cfgs": {
            "//backend:openssl-0.10": list(OPENSSL_CFGS),
            "//backend:openssl-sys-0.9": list(OPENSSL_SYS_CFGS),
        },
        "label": native_label,
        "platforms": platform_receipts,
        "version": "3.6.3",
    }


def _parse_buck(
    repo: Path,
    registry_lock: list[LockedPackage],
    local_packages: list[dict[str, str]],
    lock_sha256: str,
) -> tuple[
    bytes,
    list[dict[str, str]],
    list[str],
    list[dict[str, Any]],
    list[dict[str, str]],
    list[dict[str, Any]],
]:
    raw = _read_regular(repo, BUCK_PATH)
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as error:
        raise GraphError("backend/BUCK is not UTF-8") from error
    if not text.startswith(GENERATED_HEADER + "\n"):
        raise GraphError("backend/BUCK lacks the exact Reindeer generated header")
    if text.count(MIRROR_LOAD) != 1:
        raise GraphError("backend/BUCK must load the authenticated crate mirror exactly once")
    binding = (
        '_crate_archive_base_url = authenticated_crate_archive_base_url('
        f'"{lock_sha256}")'
    )
    if text.count(binding) != 1:
        raise GraphError("backend/BUCK is not bound to the exact Cargo.lock SHA-256")
    rules = TOP_LEVEL_RULE.findall(text)
    if not rules:
        raise GraphError("backend/BUCK contains no top-level rules")
    target_names: list[str] = []
    rules_by_name: dict[str, tuple[str, str]] = {}
    aliases: dict[str, str] = {}
    archives: list[dict[str, str]] = []
    aggregate_members: list[str] | None = None
    expected_registry = {
        (package.name, package.version): package for package in registry_lock
    }
    for kind, block in rules:
        name = _field(block, r'^    name = "([^"]+)",$', "name")
        target_names.append(name)
        rules_by_name[name] = (kind, block)
        if kind == "alias":
            aliases[name] = _field(
                block, r'^    actual = "([^"]+)",$', "alias actual"
            )
        if name == ALL_REGISTRY_ARCHIVES_TARGET:
            if kind != "filegroup" or aggregate_members is not None:
                raise GraphError("all-registry archive aggregate must be exactly one filegroup")
            srcs = re.search(r"(?ms)^    srcs = \[\n(.*?)^    \],$", block)
            if srcs is None:
                raise GraphError("all-registry archive aggregate lacks an exact srcs list")
            aggregate_members = re.findall(
                r'^        ":([^"]+\.crate)",$', srcs.group(1), re.MULTILINE
            )
            continue
        if kind == "cargo.rust_library":
            for manifest_dir in VENDOR_PATCH_MANIFEST_DIRS:
                if f'"CARGO_MANIFEST_DIR": "{manifest_dir}"' in block:
                    raise GraphError(
                        f"duplicate vendor patch owner in backend/BUCK: {manifest_dir}"
                    )
            if '    visibility = ["PUBLIC"],' not in block:
                raise GraphError(
                    f"registry Rust library {name} must be public for first-party Buck use"
                )
        if kind != "http_archive":
            continue
        sha256 = _field(block, r'^    sha256 = "([0-9a-f]+)",$', "sha256")
        strip_prefix = _field(block, r'^    strip_prefix = "([^"]+)",$', "strip_prefix")
        route = _field(
            block,
            r'^    urls = \[_crate_archive_base_url \+ "([^"]+)"\],$',
            "authenticated mirror route",
        )
        if not name.endswith(".crate"):
            raise GraphError(f"unexpected archive target name: {name}")
        stem = name[:-6]
        matches = [
            package
            for (package_name, package_version), package in expected_registry.items()
            if stem == f"{package_name}-{package_version}"
        ]
        if len(matches) != 1:
            raise GraphError(f"archive {name} resolves to {len(matches)} locked packages")
        package = matches[0]
        assert package.checksum is not None
        encoded_name = urllib.parse.quote(package.name, safe="")
        encoded_version = urllib.parse.quote(package.version, safe="")
        expected_route = f"/crates/{encoded_name}/{encoded_version}/download"
        if sha256 != package.checksum or strip_prefix != stem or route != expected_route:
            raise GraphError(f"archive {name} does not exactly match Cargo.lock/mirror route")
        archives.append(
            {
                "archive_target": f"//backend:{name}",
                "checksum": sha256,
                "name": package.name,
                "mirror_route": route,
                "version": package.version,
            }
        )
    duplicates = sorted(name for name in set(target_names) if target_names.count(name) != 1)
    if duplicates:
        raise GraphError(f"duplicate generated Buck target names: {duplicates}")

    required_buildscripts: list[dict[str, str]] = []
    for package_name, contract in sorted(REQUIRED_BUILDSCRIPT_PACKAGES.items()):
        locked = [package for package in registry_lock if package.name == package_name]
        if len(locked) != 1:
            raise GraphError(
                f"required buildscript package {package_name} resolves to {len(locked)} lock entries"
            )
        package = locked[0]
        library_target = contract["library_target"]
        build_target = f"{library_target}-build-script-build"
        runner_target = f"{library_target}-build-script-run"
        expected_rules = {
            library_target: "cargo.rust_library",
            build_target: "cargo.rust_binary",
            runner_target: "buildscript_run",
        }
        for target, expected_kind in expected_rules.items():
            actual = rules_by_name.get(target)
            if actual is None or actual[0] != expected_kind:
                raise GraphError(
                    f"required {package_name} buildscript target {target} must be {expected_kind}"
                )
        library_block = rules_by_name[library_target][1]
        out_dir = f'        "OUT_DIR": "$(location :{runner_target}[out_dir])",'
        rustc_flags = (
            f'    rustc_flags = ["@$(location :{runner_target}[rustc_flags])"],'
        )
        if library_block.count(out_dir) != 1 or library_block.count(rustc_flags) != 1:
            raise GraphError(
                f"required {package_name} library does not consume exact buildscript outputs"
            )
        archive = f"{package.name}-{package.version}.crate"
        build_block = rules_by_name[build_target][1]
        for fragment in (
            f'    srcs = [":{archive}"],',
            f'    crate_root = "{archive}/build.rs",',
            "    visibility = [],",
        ):
            if build_block.count(fragment) != 1:
                raise GraphError(
                    f"required {package_name} buildscript executable is not exact: {fragment}"
                )
        for dependency in contract["required_build_deps"]:
            if build_block.count(f'":{dependency}"') != 1:
                raise GraphError(
                    f"required {package_name} buildscript lacks dependency {dependency}"
                )
        runner_block = rules_by_name[runner_target][1]
        for fragment in (
            f'    package_name = "{package.name}",',
            f'    buildscript_rule = ":{build_target}",',
            f'    version = "{package.version}",',
        ):
            if runner_block.count(fragment) != 1:
                raise GraphError(
                    f"required {package_name} buildscript runner is not exact: {fragment}"
                )
        required_buildscripts.append(
            {
                "buildscript_target": f"//backend:{build_target}",
                "library_target": f"//backend:{library_target}",
                "package_name": package.name,
                "runner_target": f"//backend:{runner_target}",
                "version": package.version,
            }
        )
    for name, actual in EXACT_CURRENT_LOCK_ALIASES.items():
        if aliases.get(name) != actual:
            raise GraphError(
                f"current-lock alias {name} must resolve exactly to {actual}"
            )
    required_native_dependencies = [
        _validate_openssl_native_contract(repo, rules_by_name, registry_lock)
    ]
    if not archives:
        raise GraphError("backend/BUCK materializes no locked registry archives")
    archive_keys = {(item["name"], item["version"]) for item in archives}
    if len(archive_keys) != len(archives):
        raise GraphError("multiple archives materialize one locked package identity")
    expected_keys = {(package.name, package.version) for package in registry_lock}
    missing_archives = sorted(expected_keys - archive_keys)
    unexpected_archives = sorted(archive_keys - expected_keys)
    if missing_archives or unexpected_archives:
        raise GraphError(
            "backend/BUCK must materialize every registry lock identity; "
            f"missing={missing_archives}, unexpected={unexpected_archives}"
        )
    expected_aggregate_members = sorted(
        f"{package.name}-{package.version}.crate" for package in registry_lock
    )
    if aggregate_members != expected_aggregate_members:
        raise GraphError(
            "all-registry archive aggregate must contain every archive exactly once"
        )

    vendor_buckfiles: list[dict[str, Any]] = []
    for package in local_packages:
        if package["kind"] != "vendor-patch":
            continue
        package_path = Path(package["manifest"]).parent
        buck_path = package_path / "BUCK"
        raw_vendor = _read_regular(repo, buck_path)
        try:
            vendor_text = raw_vendor.decode("utf-8")
        except UnicodeDecodeError as error:
            raise GraphError(f"{buck_path.as_posix()} is not UTF-8") from error
        if "cargo.rust_library(" not in vendor_text:
            raise GraphError(f"vendor patch has no real Rust library: {buck_path.as_posix()}")
        if f'"CARGO_PKG_NAME": "{package["name"]}"' not in vendor_text:
            raise GraphError(f"vendor patch name is not exact in {buck_path.as_posix()}")
        if f'"CARGO_PKG_VERSION": "{package["version"]}"' not in vendor_text:
            raise GraphError(f"vendor patch version is not exact in {buck_path.as_posix()}")
        if 'crate_root = "src/lib.rs"' not in vendor_text:
            raise GraphError(
                f"vendor patch {package['name']} {package['version']} lacks contained crate root"
            )
        vendor_rules = TOP_LEVEL_RULE.findall(vendor_text)
        vendor_names = [
            _field(block, r'^    name = "([^"]+)",$', "vendor target name")
            for _kind, block in vendor_rules
        ]
        rust_targets = [
            name
            for (kind, _block), name in zip(vendor_rules, vendor_names, strict=True)
            if kind == "cargo.rust_library"
        ]
        if len(rust_targets) != 1:
            raise GraphError(
                f"vendor patch {package['name']} {package['version']} must own exactly one Rust library"
            )
        literal_resources = _vendor_literal_include_resources(repo, package)
        rust_block = next(
            block for kind, block in vendor_rules if kind == "cargo.rust_library"
        )
        srcs = re.search(r"(?ms)^    srcs = \[\n(.*?)^    \],$", rust_block)
        if srcs is None:
            raise GraphError(
                f"vendor patch {package['name']} {package['version']} lacks exact srcs"
            )
        staged = re.findall(r'^        "([^"]+)",$', srcs.group(1), re.MULTILINE)
        if len(staged) != len(set(staged)):
            raise GraphError(f"vendor patch has duplicate staged sources: {buck_path.as_posix()}")
        for resource in literal_resources:
            if staged.count(resource["path"]) != 1:
                raise GraphError(
                    "vendor literal include resource must be staged exactly once: "
                    f"{package_path.as_posix()}/{resource['path']}"
                )
        label = f"//{package_path.as_posix()}:{rust_targets[0]}"
        package["buck_label"] = label
        vendor_buckfiles.append(
            {
                "path": buck_path.as_posix(),
                "sha256": hashlib.sha256(raw_vendor).hexdigest(),
                "target": label,
                "literal_include_resources": literal_resources,
            }
        )
    targets = sorted(
        [*(f"//backend:{name}" for name in target_names), *(item["target"] for item in vendor_buckfiles)]
    )
    return (
        raw,
        sorted(archives, key=lambda item: (item["name"], item["version"])),
        targets,
        sorted(vendor_buckfiles, key=lambda item: item["path"]),
        required_buildscripts,
        required_native_dependencies,
    )


def build_receipt(repo: Path) -> dict[str, Any]:
    repo = repo.resolve(strict=True)
    lock_raw, packages = _load_lock(repo)
    registry = [package for package in packages if package.source == REGISTRY_SOURCE]
    local = [package for package in packages if package.source is None]
    local_packages = _discover_local_manifests(repo, local)
    lock_sha256 = hashlib.sha256(lock_raw).hexdigest()
    (
        buck_raw,
        materialized,
        buck_targets,
        vendor_buckfiles,
        required_buildscripts,
        required_native_dependencies,
    ) = _parse_buck(repo, registry, local_packages, lock_sha256)
    (
        canonical_sqlx_migrations,
        canonical_sqlx_migration_staging,
        canonical_sqlx_migration_identity_source,
    ) = _canonical_sqlx_migration_contract(repo)
    materialized_keys = {(item["name"], item["version"]) for item in materialized}
    omitted = [
        {
            "checksum": package.checksum,
            "name": package.name,
            "source": package.source,
            "version": package.version,
        }
        for package in registry
        if (package.name, package.version) not in materialized_keys
    ]
    registry_packages = [
        {
            "checksum": package.checksum,
            "name": package.name,
            "source": package.source,
            "version": package.version,
        }
        for package in registry
    ]
    return {
        "artifact_kind": "CURRENT_LOCK_BUCK2_RUST_GRAPH",
        "schema_version": 1,
        "generated_by": "tools/buck/current_lock_rust_graph.py",
        "reindeer_commit": REINDEER_COMMIT,
        "authority_boundary": (
            "Cargo.lock is immutable dependency input; checked-in Buck2 labels and Buck2 "
            "execution are build/test authority. Cargo is not invoked by this verifier."
        ),
        "lockfile": LOCK_PATH.as_posix(),
        "lock_sha256": lock_sha256,
        "buckfile": BUCK_PATH.as_posix(),
        "buck_sha256": hashlib.sha256(buck_raw).hexdigest(),
        "buckfiles": [
            {
                "path": BUCK_PATH.as_posix(),
                "sha256": hashlib.sha256(buck_raw).hexdigest(),
            },
            *vendor_buckfiles,
        ],
        "canonical_sqlx_migrations": canonical_sqlx_migrations,
        "canonical_sqlx_migration_staging": canonical_sqlx_migration_staging,
        "canonical_sqlx_migration_identity_source": {
            "path": SQLX_MIGRATION_IDENTITY_SOURCE_PATH.as_posix(),
            "sha256": hashlib.sha256(
                canonical_sqlx_migration_identity_source.encode("utf-8")
            ).hexdigest(),
        },
        "package_count": len(packages),
        "registry_package_count": len(registry_packages),
        "registry_packages": registry_packages,
        "materialized_registry_package_count": len(materialized),
        "materialized_registry_packages": materialized,
        "omitted_registry_package_count": len(omitted),
        "omitted_registry_packages": omitted,
        "local_package_count": len(local_packages),
        "local_packages": local_packages,
        "buck_target_count": len(buck_targets),
        "buck_targets": buck_targets,
        "required_buildscripts": required_buildscripts,
        "required_native_dependencies": required_native_dependencies,
    }


def _render(receipt: dict[str, Any]) -> str:
    return json.dumps(receipt, indent=2, sort_keys=True) + "\n"


def check_receipt(repo: Path) -> None:
    repo = repo.resolve(strict=True)
    receipt = build_receipt(repo)
    expected_identity_source = _render_sqlx_migration_identity_source(
        receipt["canonical_sqlx_migrations"]
    ).encode("utf-8")
    if _read_regular(repo, SQLX_MIGRATION_IDENTITY_SOURCE_PATH) != expected_identity_source:
        raise GraphError(
            f"{SQLX_MIGRATION_IDENTITY_SOURCE_PATH.as_posix()} is stale"
        )
    expected = _render(receipt)
    current = _read_regular(repo, RECEIPT_PATH).decode("utf-8")
    if current != expected:
        raise GraphError(f"{RECEIPT_PATH.as_posix()} is stale")


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp", text=True
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o644)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    repo = _repo_root()
    try:
        receipt = build_receipt(repo)
        rendered = _render(receipt)
        output = repo / RECEIPT_PATH
        if args.write:
            _write_atomic(
                repo / SQLX_MIGRATION_IDENTITY_SOURCE_PATH,
                _render_sqlx_migration_identity_source(
                    receipt["canonical_sqlx_migrations"]
                ),
            )
            _write_atomic(output, rendered)
            print(f"wrote {RECEIPT_PATH.as_posix()}")
        else:
            check_receipt(repo)
            print(
                "current-lock Rust graph exact: "
                f"{json.loads(rendered)['buck_target_count']} Buck targets"
            )
    except (GraphError, OSError, ValueError) as error:
        print(f"current-lock-rust-graph: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
