# @generated by scripts/lock-rust-toolchain.mjs from //rust-toolchain.toml -- do not edit.
#
# Hash-pinned Rust toolchain artifacts. buck2 materializes these as build
# INPUTS, so the compiler's bytes are inside every action's input tree and
# therefore inside its digest. A different compiler is a different action:
# a cache miss, not the unlinkable-artifact hit that was #1083.

RUST_CHANNEL = "1.97.1"

# package -> target triple -> (url, sha256)
RUST_DIST = {
    "clippy-preview": {
        "aarch64-apple-darwin": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/clippy-1.97.1-aarch64-apple-darwin.tar.xz",
            "sha256": "5e44c0ac5ca9b6f14a3c9031a61f583348b902f908f46e95717aef1dbd2807db",
        },
        "x86_64-unknown-linux-gnu": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/clippy-1.97.1-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "3441df8fb54db985f8c8a3e8356b8874a3f92cc8cca8565cfe36f1dc15935e72",
        },
    },
    "rust-std": {
        "aarch64-apple-darwin": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/rust-std-1.97.1-aarch64-apple-darwin.tar.xz",
            "sha256": "a4895f5c6995e83cab8687e46b14324592398049def71ce75ca308c981cf200d",
        },
        "wasm32-unknown-unknown": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/rust-std-1.97.1-wasm32-unknown-unknown.tar.xz",
            "sha256": "fa0edb6e9f34faae5735554d62d50875eded839dc707d0f1c01467a918d8453b",
        },
        "x86_64-unknown-linux-gnu": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/rust-std-1.97.1-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "1c1e704ae80126b7de34f72ea2825f7fd01736dec20732faed47374b95282fba",
        },
    },
    "rustc": {
        "aarch64-apple-darwin": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/rustc-1.97.1-aarch64-apple-darwin.tar.xz",
            "sha256": "6076cad38ccabaa24325f26a74080a363a2633a9cd34c473a8977255d8a593cb",
        },
        "x86_64-unknown-linux-gnu": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/rustc-1.97.1-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "9819d0a32d56bd339585319c80260e332779f5541fd66838ab7e016d6c814819",
        },
    },
    "rustfmt-preview": {
        "aarch64-apple-darwin": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/rustfmt-1.97.1-aarch64-apple-darwin.tar.xz",
            "sha256": "358bbba5d0c7c37116ec15f67cfd3ac4da5d3c319cddb49389c26d3a0c65747a",
        },
        "x86_64-unknown-linux-gnu": {
            "url": "https://static.rust-lang.org/dist/2026-07-16/rustfmt-1.97.1-x86_64-unknown-linux-gnu.tar.xz",
            "sha256": "907fe97d6afbde1eca1b34c992c76e1406d422e2e6f137813d382acec7eb4d14",
        },
    },
}
