import { useCallback, useEffect, useState, type CSSProperties, type FormEvent } from "react";
import type { components } from "@maintenance/api-client-ts";
import { useAuth } from "../../context/auth";
import "../tokens.css";

type Engagement = components["schemas"]["ConsultingEngagement"];
type Detail = components["schemas"]["ConsultingEngagementDetail"];
type Page = components["schemas"]["ConsultingEngagementPage"];
const page: CSSProperties = { height: "100%", overflowY: "auto", padding: "var(--sp-6)", background: "var(--canvas)", color: "var(--ink)" };
const panel: CSSProperties = { border: "var(--border-hairline)", borderRadius: "var(--radius-card)", background: "var(--surface)", padding: "var(--sp-4)", display: "grid", gap: "var(--sp-3)" };
const button: CSSProperties = { minHeight: 40, padding: "0 var(--sp-3)", border: "1px solid var(--accent)", borderRadius: "var(--radius-sm)", background: "var(--accent)", color: "var(--on-accent)", font: "inherit", cursor: "pointer" };
const input: CSSProperties = { minHeight: 40, width: "100%", boxSizing: "border-box", border: "var(--border-hairline)", borderRadius: "var(--radius-sm)", padding: "0 var(--sp-2)", background: "var(--surface)", color: "var(--ink)" };
function message(error: unknown) { const value = error as { error?: { message?: string } }; return value?.error?.message ?? "요청을 완료하지 못했습니다."; }
function ids(detail: Detail) { return { diagnosticId: detail.diagnostics.at(-1)?.id, findingId: detail.findings.at(-1)?.id, initiativeId: detail.initiatives.at(-1)?.id }; }

/** Real API console vertical; every control either performs a supported mutation or is absent. */
export function ConsultingEngagementBody() {
  const { api: authority } = useAuth(); const [data, setData] = useState<Page>(); const [selected, setSelected] = useState<Detail>();
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); const r = await authority.GET("/api/v1/consulting/engagements", { params: { query: { limit: 25, offset: 0 } } }).catch(() => undefined); setLoading(false); if (!r?.data) { setError(message(r?.error)); return; } setError(undefined); setData(r.data); }, [authority]);
  const detail = useCallback(async (id: string) => { setBusy(true); const r = await authority.GET("/api/v1/consulting/engagements/{engagement_id}", { params: { path: { engagement_id: id } } }).catch(() => undefined); setBusy(false); if (!r?.data) { setError(message(r?.error)); return; } setError(undefined); setSelected(r.data); }, [authority]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); const documentId = String(f.get("documentId")) || undefined; const ontologyId = String(f.get("ontologyId")) || undefined; const r = await authority.POST("/api/v1/consulting/engagements", { body: { customerId: String(f.get("customerId")), title: String(f.get("title")), idempotencyKey: crypto.randomUUID(), customerDocumentId: documentId, ontologyInstanceId: ontologyId } }).catch(() => undefined); setBusy(false); if (!r?.data) { setError(message(r?.error)); return; } event.currentTarget.reset(); await load(); await detail(r.data.id); }
  async function post(path: "/api/v1/consulting/engagements/{engagement_id}/diagnostics" | "/api/v1/consulting/engagements/{engagement_id}/findings" | "/api/v1/consulting/engagements/{engagement_id}/initiatives" | "/api/v1/consulting/engagements/{engagement_id}/observations", body: object) { if (!selected) return; setBusy(true); const r = await authority.POST(path, { params: { path: { engagement_id: selected.id } }, body: body as never }).catch(() => undefined); setBusy(false); if (!r?.data) { setError(message(r?.error)); return; } await detail(selected.id); }
  async function advance(toStatus: "PROPOSED" | "APPROVED" | "IMPLEMENTED" | "MEASURED" | "SUSTAINED" | "CORRECTIVE") { if (!selected) return; const r = await authority.POST("/api/v1/consulting/engagements/{engagement_id}/transition", { params: { path: { engagement_id: selected.id } }, body: { toStatus, expectedVersion: selected.version, reason: `console:${toStatus.toLowerCase()}`, approvalId: toStatus === "APPROVED" ? crypto.randomUUID() : undefined, workflowExecutionId: undefined } }).catch(() => undefined); if (!r?.data) { setError(message(r?.error)); return; } await detail(selected.id); await load(); }
  const chain: { diagnosticId?: string; findingId?: string; initiativeId?: string } = selected ? ids(selected) : {};
  return <section aria-label="컨설팅 실행" style={page}><header style={{ display: "flex", justifyContent: "space-between", gap: "var(--sp-3)", flexWrap: "wrap" }}><h1 style={{ margin: 0 }}>컨설팅 실행 · 실현효익</h1><button onClick={() => void load()} style={button}>새로고침</button></header>
    <form onSubmit={create} style={{ ...panel, marginTop: "var(--sp-4)", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))" }}><input required name="customerId" aria-label="고객 ID" placeholder="고객 UUID" style={input}/><input required name="title" aria-label="참여 제목" placeholder="참여 제목" style={input}/><input name="documentId" aria-label="고객 문서 ID" placeholder="고객 문서 UUID (선택)" style={input}/><input name="ontologyId" aria-label="온톨로지 인스턴스 ID" placeholder="온톨로지 UUID (선택)" style={input}/><button disabled={busy} style={button}>참여 생성</button></form>
    {loading ? <p role="status">불러오는 중…</p> : null}{error ? <div role="alert" style={panel}>{error}<button onClick={() => void load()} style={button}>다시 시도</button></div> : null}
    {!loading && !error && data?.items.length === 0 ? <div role="status" style={panel}>표시할 컨설팅 참여가 없습니다.</div> : null}
    <div style={{ display: "grid", gridTemplateColumns: "minmax(260px,1fr) minmax(320px,2fr)", gap: "var(--sp-4)", marginTop: "var(--sp-4)" }}><div style={{ display: "grid", gap: "var(--sp-2)" }}>{data?.items.map((item: Engagement) => <button key={item.id} onClick={() => void detail(item.id)} style={{ ...panel, textAlign: "left", cursor: "pointer" }}><b>{item.title}</b><span>{item.status} · v{item.version}</span></button>)}</div>
      <div>{selected ? <article style={panel}><header><h2 style={{ margin: 0 }}>{selected.title}</h2><span>{selected.status} · v{selected.version}</span></header><div style={{ display: "flex", flexWrap: "wrap", gap: "var(--sp-2)" }}>
        {selected.status === "DRAFT" ? <button style={button} onClick={() => void advance("PROPOSED")}>제안 상신</button> : null}{selected.status === "PROPOSED" ? <button style={button} onClick={() => void advance("APPROVED")}>승인 기록</button> : null}{selected.status === "APPROVED" ? <button style={button} onClick={() => void advance("IMPLEMENTED")}>구현 검토 완료</button> : null}{selected.status === "IMPLEMENTED" ? <button style={button} onClick={() => void advance("MEASURED")}>측정 단계로</button> : null}{selected.status === "MEASURED" ? <><button style={button} onClick={() => void advance("SUSTAINED")}>지속 결정</button><button style={button} onClick={() => void advance("CORRECTIVE")}>시정 결정</button></> : null}</div>
        <ChainForm title="진단" disabled={busy} fields={["summary", "documentId"]} onSubmit={(f) => void post("/api/v1/consulting/engagements/{engagement_id}/diagnostics", { summary: f.summary, documentId: f.documentId || null })}/>
        {chain.diagnosticId ? <ChainForm title="증거 연결 발견" disabled={busy} fields={["statement", "evidenceId", "documentId"]} onSubmit={(f) => void post("/api/v1/consulting/engagements/{engagement_id}/findings", { diagnosticId: chain.diagnosticId, statement: f.statement, evidenceId: f.evidenceId, documentId: f.documentId || null })}/> : null}
        {chain.findingId ? <ChainForm title="이니셔티브·효익 가설" disabled={busy} fields={["title", "hypothesis", "kpiDefinitionId", "targetDirection"]} onSubmit={(f) => void post("/api/v1/consulting/engagements/{engagement_id}/initiatives", { findingId: chain.findingId, title: f.title, hypothesis: f.hypothesis, kpiDefinitionId: f.kpiDefinitionId, targetDirection: f.targetDirection })}/> : null}
        {chain.initiativeId && selected.status === "IMPLEMENTED" ? <ChainForm title="KPI·증거 관측" disabled={busy} fields={["kpiDefinitionId", "evidenceId", "observedAt", "note"]} onSubmit={(f) => void post("/api/v1/consulting/engagements/{engagement_id}/observations", { initiativeId: chain.initiativeId, kpiDefinitionId: f.kpiDefinitionId, evidenceId: f.evidenceId, observedAt: f.observedAt, note: f.note })}/> : null}
        <section><h3>추적 연결</h3><ul>{selected.diagnostics.map(v => <li key={v.id}>진단 {v.id} · 문서 {v.document_id ?? "없음"}</li>)}{selected.findings.map(v => <li key={v.id}>발견 {v.id} · 증거 {v.evidence_id}</li>)}{selected.initiatives.map(v => <li key={v.id}>이니셔티브 {v.id} · KPI 정의 {v.kpi_definition_id}</li>)}{selected.observations.map(v => <li key={v.id}>관측 {v.id} · KPI 정의 {v.kpi_definition_id} · 증거 {v.evidence_id}</li>)}</ul></section>
      </article> : <div style={panel}>왼쪽에서 참여를 선택하면 상세 이력과 다음 허용 작업이 표시됩니다.</div>}</div></div></section>;
}
function ChainForm({ title, fields, onSubmit, disabled }: { title: string; fields: string[]; disabled: boolean; onSubmit: (v: Record<string, string>) => void }) { return <form onSubmit={(e) => { e.preventDefault(); onSubmit(Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string, string>); }} style={{ ...panel, gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))" }}><b>{title}</b>{fields.map(field => field === "targetDirection" ? <select key={field} name={field} aria-label={field} style={input}><option value="INCREASE">INCREASE</option><option value="DECREASE">DECREASE</option></select> : <input key={field} required name={field} aria-label={field} type={field === "observedAt" ? "datetime-local" : "text"} placeholder={field} style={input}/>)}<button disabled={disabled} style={button}>기록</button></form>; }
