import { FormEvent, useCallback, useEffect, useId, useState } from "react";
import { productionApi, type ProductionPlan, type ProductionPlanDetail } from "./productionApi";

const key = () => crypto.randomUUID();
/** Route adapter passes authenticated session roles; callers cannot forge action booleans. */
type Props = { branchId: string; roles: readonly string[] };

export function ProductionScreen({ branchId, roles }: Props) {
  const canPlan = roles.includes("ADMIN") || roles.includes("EXECUTIVE");
  const canRelease = roles.includes("ADMIN") || roles.includes("EXECUTIVE");
  const canRecord = canPlan || roles.includes("MECHANIC");
  const [plans, setPlans] = useState<ProductionPlan[]>([]); const [selected, setSelected] = useState<ProductionPlanDetail | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const demandId = useId(); const productId = useId(); const evidenceId = useId();
  const load = useCallback(async () => { setLoading(true); setError(null); try { setPlans(await productionApi.list(branchId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load production plans."); } finally { setLoading(false); } }, [branchId]);
  useEffect(() => { void load(); }, [load]);
  async function choose(id: string) { setBusy(true); setError(null); try { setSelected(await productionApi.get(id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load plan history."); } finally { setBusy(false); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!canPlan) return; const data = new FormData(event.currentTarget); setBusy(true); setError(null); try { const plan = await productionApi.create({ branch_id: branchId, customer_demand_id: String(data.get("demand")), capacity_slot_id: String(data.get("capacity")), material_item_id: String(data.get("material")), quantity: Number(data.get("quantity")), due_at: new Date(String(data.get("due"))).toISOString(), approval_ref: String(data.get("approval")), ontology_type_id: String(data.get("ontology")), idempotency_key: key() }); await load(); await choose(plan.id); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create production plan."); } finally { setBusy(false); } }
  async function release() { if (!selected || !canRelease) return; setBusy(true); setError(null); try { await productionApi.release(selected.id, selected.version, key()); await choose(selected.id); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not release production plan."); } finally { setBusy(false); } }
  async function record(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected || !canRecord) return; const data = new FormData(event.currentTarget); setBusy(true); setError(null); try { await productionApi.record(selected.id, selected.operation.id, { expected_version: selected.operation.version, idempotency_key: key(), output_quantity: Number(data.get("output")), scrap_quantity: Number(data.get("scrap")), downtime_minutes: Number(data.get("downtime")), quality_evidence_ref: String(data.get("evidence")), quality_passed: data.get("quality") === "pass", note: String(data.get("note")) }); await choose(selected.id); await load(); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not record operation evidence."); } finally { setBusy(false); } }
  return <main className="mx-auto grid max-w-7xl gap-4 p-4 lg:grid-cols-[minmax(19rem,1fr)_minmax(0,2fr)]" aria-busy={loading || busy}>
    <section aria-labelledby="production-title" className="min-w-0 space-y-4"><header><h1 id="production-title" className="text-xl font-semibold">Production plans</h1><p className="text-sm text-muted-foreground">Tenant-scoped subcontracting execution with durable lineage.</p></header>
      {error && <div role="alert" className="rounded border border-destructive p-3 text-sm">{error} <button type="button" className="underline" onClick={() => void load()}>Retry</button></div>}
      {loading ? <p role="status">Loading production plans…</p> : plans.length === 0 ? <p role="status" className="rounded border p-4">No production plans for this branch. Create one after verifying demand, capacity, materials, and staffing.</p> : <ul aria-label="Production plans" className="divide-y rounded border">{plans.map((plan) => <li key={plan.id}><button type="button" className="w-full p-3 text-left focus-visible:outline focus-visible:outline-2" onClick={() => void choose(plan.id)}><span className="font-medium">{plan.product_code}</span><span className="ml-2 text-sm">{plan.quantity} · {plan.status}</span></button></li>)}</ul>}
      {canPlan ? <form onSubmit={create} className="grid gap-2 rounded border p-3 sm:grid-cols-2"><h2 className="sm:col-span-2 font-medium">Create checked plan</h2><label htmlFor={demandId}>Customer demand ID</label><input id={demandId} name="demand" required /><label htmlFor={productId}>Capacity slot ID</label><input id={productId} name="capacity" required /><label>Material item ID<input name="material" required /></label><label>Quantity<input name="quantity" type="number" min="1" required /></label><label>Due at<input name="due" type="datetime-local" required /></label><label>Approved request ID<input name="approval" required /></label><label>Published ontology type ID<input name="ontology" required /></label><button disabled={busy} type="submit">Create plan</button></form> : <p role="status">You are not authorized to create production plans.</p>}</section>
    <section aria-live="polite" className="min-w-0 space-y-4">{!selected ? <p className="rounded border p-4">Choose a plan to inspect checks, operation state, and lifecycle evidence.</p> : <><header><h2 className="text-lg font-semibold">{selected.product_code}</h2><p>{selected.status} · version {selected.version}</p></header><dl className="grid grid-cols-2 gap-2 rounded border p-3 text-sm"><dt>Demand</dt><dd className="break-all">{selected.customer_demand_id}</dd><dt>Operation</dt><dd>{selected.operation.status}</dd><dt>Output / scrap</dt><dd>{selected.operation.output_quantity} / {selected.operation.scrap_quantity}</dd><dt>Downtime</dt><dd>{selected.operation.downtime_minutes} minutes</dd></dl>{selected.status === "DRAFT" && (canRelease ? <button disabled={busy} onClick={() => void release()}>Release first operation</button> : <p role="status">You are not authorized to release this plan.</p>)}{selected.status === "RELEASED" && (canRecord ? <form onSubmit={record} className="grid gap-2 rounded border p-3"><h3 className="font-medium">Record operation</h3><label>Output<input name="output" type="number" min="0" required /></label><label>Scrap<input name="scrap" type="number" min="0" required /></label><label>Downtime minutes<input name="downtime" type="number" min="0" required /></label><label htmlFor={evidenceId}>Quality evidence reference</label><input id={evidenceId} name="evidence" required /><fieldset><legend>Quality result</legend><label><input name="quality" type="radio" value="pass" defaultChecked /> Pass</label><label><input name="quality" type="radio" value="fail" /> Fail</label></fieldset><label>Note<textarea name="note" maxLength={500} required /></label><button disabled={busy} type="submit">Record evidence</button></form> : <p role="status">You are not authorized to record this operation.</p>)}<section><h3 className="font-medium">Durable lineage</h3><ol className="space-y-2">{selected.events.map((event) => <li key={event.id} className="border-l-2 pl-3"><strong>{event.event_type}</strong><div className="text-sm">{new Date(event.occurred_at).toLocaleString()}</div></li>)}</ol></section></>}</section>
  </main>;
}
