import { FormEvent, useCallback, useEffect, useId, useState } from "react";
import { productionApi, type ProductionPlan, type ProductionPlanDetail } from "./productionApi";
import "./production.css";

const key = () => crypto.randomUUID();
const ko = {
  title: "생산 계획", subtitle: "테넌트 범위의 생산 실행과 변경 이력을 관리합니다.", retry: "다시 시도",
  loading: "생산 계획을 불러오는 중입니다…", empty: "이 지점에는 생산 계획이 없습니다.", create: "검증된 계획 생성",
  demand: "수요 계약 ID", capacity: "용량 슬롯 ID", material: "자재 품목 ID", quantity: "수량", due: "납기", approval: "승인 ID", ontology: "게시된 온톨로지 유형 ID",
  noPlan: "생산 계획 생성 권한이 없습니다.", select: "계획을 선택하여 검증 결과와 이력을 확인하세요.", release: "첫 작업 출시", record: "작업 실적 기록",
  output: "생산 수량", scrap: "불량 수량", downtime: "비가동 시간(분)", evidence: "품질 증빙 참조", quality: "품질 결과", pass: "통과", fail: "실패", note: "메모", lineage: "변경 이력",
  demandLabel: "수요", operation: "작업", totals: "생산 / 불량", errorLoad: "생산 계획을 불러오지 못했습니다.", errorCreate: "생산 계획을 생성하지 못했습니다.", errorRelease: "계획을 출시하지 못했습니다.", errorRecord: "작업 실적을 기록하지 못했습니다.",
};
type Props = { branchId: string; roles: readonly string[] };

export function ProductionScreen({ branchId, roles }: Props) {
  const canPlan = roles.includes("ADMIN") || roles.includes("EXECUTIVE");
  const canRelease = canPlan;
  const canRecord = canPlan || roles.includes("MECHANIC");
  const [plans, setPlans] = useState<ProductionPlan[]>([]);
  const [selected, setSelected] = useState<ProductionPlanDetail | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const demandId = useId(); const capacityId = useId(); const evidenceId = useId();
  const load = useCallback(async () => { setLoading(true); setError(null); try { setPlans(await productionApi.list(branchId)); } catch (cause) { setError(cause instanceof Error ? cause.message : ko.errorLoad); } finally { setLoading(false); } }, [branchId]);
  useEffect(() => { void load(); }, [load]);
  const choose = async (id: string) => { setBusy(true); try { setSelected(await productionApi.get(id)); } catch (cause) { setError(cause instanceof Error ? cause.message : ko.errorLoad); } finally { setBusy(false); } };
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); try { const plan = await productionApi.create({ branch_id: branchId, customer_demand_id: String(data.get("demand")), capacity_slot_id: String(data.get("capacity")), material_item_id: String(data.get("material")), quantity: Number(data.get("quantity")), due_at: new Date(String(data.get("due"))).toISOString(), approval_ref: String(data.get("approval")), ontology_type_id: String(data.get("ontology")), idempotency_key: key() }); await load(); await choose(plan.id); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : ko.errorCreate); } finally { setBusy(false); } };
  const release = async () => { if (!selected) return; setBusy(true); try { await productionApi.release(selected.id, selected.version, key()); await choose(selected.id); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : ko.errorRelease); } finally { setBusy(false); } };
  const record = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); setBusy(true); try { await productionApi.record(selected.id, selected.operation.id, { expected_version: selected.operation.version, idempotency_key: key(), output_quantity: Number(data.get("output")), scrap_quantity: Number(data.get("scrap")), downtime_minutes: Number(data.get("downtime")), quality_evidence_ref: String(data.get("evidence")), quality_passed: data.get("quality") === "pass", note: String(data.get("note")) }); await choose(selected.id); await load(); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : ko.errorRecord); } finally { setBusy(false); } };
  return <main className="production" aria-busy={loading || busy}><section className="production__panel"><header><h1>{ko.title}</h1><p>{ko.subtitle}</p></header>{error && <div role="alert" className="production__alert">{error}<button onClick={() => void load()} type="button">{ko.retry}</button></div>}{loading ? <p role="status">{ko.loading}</p> : <ul aria-label={ko.title} className="production__list">{plans.length ? plans.map((plan) => <li key={plan.id}><button type="button" onClick={() => void choose(plan.id)}>{plan.product_code} · {plan.quantity} · {plan.status}</button></li>) : <li role="status">{ko.empty}</li>}</ul>}{canPlan && <form className="production__form" onSubmit={(event) => void create(event)}><h2>{ko.create}</h2><label htmlFor={demandId}>{ko.demand}</label><input id={demandId} name="demand" required /><label htmlFor={capacityId}>{ko.capacity}</label><input id={capacityId} name="capacity" required /><label>{ko.material}<input name="material" required /></label><label>{ko.quantity}<input name="quantity" type="number" min="1" required /></label><label>{ko.due}<input name="due" type="datetime-local" required /></label><label>{ko.approval}<input name="approval" required /></label><label>{ko.ontology}<input name="ontology" required /></label><button disabled={busy}>{ko.create}</button></form>}</section><section className="production__panel" aria-live="polite">{!selected ? <p>{ko.select}</p> : <><h2>{selected.product_code}</h2><dl><dt>{ko.demandLabel}</dt><dd>{selected.customer_demand_id}</dd><dt>{ko.operation}</dt><dd>{selected.operation.status}</dd><dt>{ko.totals}</dt><dd>{selected.operation.output_quantity} / {selected.operation.scrap_quantity}</dd></dl>{selected.status === "DRAFT" && canRelease && <button disabled={busy} onClick={() => void release()}>{ko.release}</button>}{selected.status === "RELEASED" && canRecord && <form className="production__form" onSubmit={(event) => void record(event)}><h3>{ko.record}</h3><label>{ko.output}<input name="output" type="number" min="0" required /></label><label>{ko.scrap}<input name="scrap" type="number" min="0" required /></label><label>{ko.downtime}<input name="downtime" type="number" min="0" required /></label><label htmlFor={evidenceId}>{ko.evidence}</label><input id={evidenceId} name="evidence" required /><fieldset><legend>{ko.quality}</legend><label><input name="quality" type="radio" value="pass" defaultChecked />{ko.pass}</label><label><input name="quality" type="radio" value="fail" />{ko.fail}</label></fieldset><label>{ko.note}<textarea name="note" maxLength={500} required /></label><button disabled={busy}>{ko.record}</button></form>}<h3>{ko.lineage}</h3><ol>{selected.events.map((event) => <li key={event.id}>{event.event_type} · {new Date(event.occurred_at).toLocaleString("ko-KR")}</li>)}</ol></>}</section></main>;
}
