/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.Equipment3rApproval
import com.maintenance.api.client.model.Equipment3rAssessment
import com.maintenance.api.client.model.Equipment3rDispatch
import com.maintenance.api.client.model.Equipment3rDisposition
import com.maintenance.api.client.model.Equipment3rDispositionCompletion
import com.maintenance.api.client.model.Equipment3rHandover
import com.maintenance.api.client.model.Equipment3rHistoryEntry
import com.maintenance.api.client.model.Equipment3rInspection
import com.maintenance.api.client.model.Equipment3rInspectionRequest
import com.maintenance.api.client.model.Equipment3rQuoteCase
import com.maintenance.api.client.model.Equipment3rRegisterUnit
import com.maintenance.api.client.model.Equipment3rRentalCase
import com.maintenance.api.client.model.Equipment3rRentalCaseDetail
import com.maintenance.api.client.model.Equipment3rReturn
import com.maintenance.api.client.model.Equipment3rUnit
import com.maintenance.api.client.model.Equipment3rUnitDetail
import com.maintenance.api.client.model.ErrorBody

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class Equipment3rApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/assessment
     * Bind a returned Equipment 3R unit to repair, refurbishment, resale, or redeploy
     *
     * @param caseId
     * @param equipment3rAssessment
     * @return Equipment3rRentalCaseDetail
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun assessEquipment3rRentalReturn(caseId: java.util.UUID, equipment3rAssessment: Equipment3rAssessment) : Equipment3rRentalCaseDetail = withContext(Dispatchers.IO) {
        val localVarResponse = assessEquipment3rRentalReturnWithHttpInfo(caseId = caseId, equipment3rAssessment = equipment3rAssessment)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rRentalCaseDetail
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/assessment
     * Bind a returned Equipment 3R unit to repair, refurbishment, resale, or redeploy
     *
     * @param caseId
     * @param equipment3rAssessment
     * @return ApiResponse<Equipment3rRentalCaseDetail?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun assessEquipment3rRentalReturnWithHttpInfo(caseId: java.util.UUID, equipment3rAssessment: Equipment3rAssessment) : ApiResponse<Equipment3rRentalCaseDetail?> = withContext(Dispatchers.IO) {
        val localVariableConfig = assessEquipment3rRentalReturnRequestConfig(caseId = caseId, equipment3rAssessment = equipment3rAssessment)

        return@withContext request<Equipment3rAssessment, Equipment3rRentalCaseDetail>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation assessEquipment3rRentalReturn
     *
     * @param caseId
     * @param equipment3rAssessment
     * @return RequestConfig
     */
    fun assessEquipment3rRentalReturnRequestConfig(caseId: java.util.UUID, equipment3rAssessment: Equipment3rAssessment) : RequestConfig<Equipment3rAssessment> {
        val localVariableBody = equipment3rAssessment
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/rental-cases/{case_id}/assessment".replace("{"+"case_id"+"}", encodeURIComponent(caseId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/dispositions/{disposition_id}/completion
     * Complete an Equipment 3R repair, refurbishment, or resale disposition
     *
     * @param dispositionId
     * @param equipment3rDispositionCompletion
     * @return Equipment3rDisposition
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun completeEquipment3rDisposition(dispositionId: java.util.UUID, equipment3rDispositionCompletion: Equipment3rDispositionCompletion) : Equipment3rDisposition = withContext(Dispatchers.IO) {
        val localVarResponse = completeEquipment3rDispositionWithHttpInfo(dispositionId = dispositionId, equipment3rDispositionCompletion = equipment3rDispositionCompletion)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rDisposition
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/dispositions/{disposition_id}/completion
     * Complete an Equipment 3R repair, refurbishment, or resale disposition
     *
     * @param dispositionId
     * @param equipment3rDispositionCompletion
     * @return ApiResponse<Equipment3rDisposition?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun completeEquipment3rDispositionWithHttpInfo(dispositionId: java.util.UUID, equipment3rDispositionCompletion: Equipment3rDispositionCompletion) : ApiResponse<Equipment3rDisposition?> = withContext(Dispatchers.IO) {
        val localVariableConfig = completeEquipment3rDispositionRequestConfig(dispositionId = dispositionId, equipment3rDispositionCompletion = equipment3rDispositionCompletion)

        return@withContext request<Equipment3rDispositionCompletion, Equipment3rDisposition>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation completeEquipment3rDisposition
     *
     * @param dispositionId
     * @param equipment3rDispositionCompletion
     * @return RequestConfig
     */
    fun completeEquipment3rDispositionRequestConfig(dispositionId: java.util.UUID, equipment3rDispositionCompletion: Equipment3rDispositionCompletion) : RequestConfig<Equipment3rDispositionCompletion> {
        val localVariableBody = equipment3rDispositionCompletion
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/dispositions/{disposition_id}/completion".replace("{"+"disposition_id"+"}", encodeURIComponent(dispositionId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/approval
     * Record a four-eyes approval decision for an Equipment 3R rental case
     *
     * @param caseId
     * @param equipment3rApproval
     * @return Equipment3rRentalCase
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun decideEquipment3rRentalCase(caseId: java.util.UUID, equipment3rApproval: Equipment3rApproval) : Equipment3rRentalCase = withContext(Dispatchers.IO) {
        val localVarResponse = decideEquipment3rRentalCaseWithHttpInfo(caseId = caseId, equipment3rApproval = equipment3rApproval)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rRentalCase
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/approval
     * Record a four-eyes approval decision for an Equipment 3R rental case
     *
     * @param caseId
     * @param equipment3rApproval
     * @return ApiResponse<Equipment3rRentalCase?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun decideEquipment3rRentalCaseWithHttpInfo(caseId: java.util.UUID, equipment3rApproval: Equipment3rApproval) : ApiResponse<Equipment3rRentalCase?> = withContext(Dispatchers.IO) {
        val localVariableConfig = decideEquipment3rRentalCaseRequestConfig(caseId = caseId, equipment3rApproval = equipment3rApproval)

        return@withContext request<Equipment3rApproval, Equipment3rRentalCase>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation decideEquipment3rRentalCase
     *
     * @param caseId
     * @param equipment3rApproval
     * @return RequestConfig
     */
    fun decideEquipment3rRentalCaseRequestConfig(caseId: java.util.UUID, equipment3rApproval: Equipment3rApproval) : RequestConfig<Equipment3rApproval> {
        val localVariableBody = equipment3rApproval
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/rental-cases/{case_id}/approval".replace("{"+"case_id"+"}", encodeURIComponent(caseId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/dispatch
     * Record the carrier and vehicle dispatch leg for an approved Equipment 3R case
     *
     * @param caseId
     * @param equipment3rDispatch
     * @return Equipment3rRentalCase
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun dispatchEquipment3rRentalCase(caseId: java.util.UUID, equipment3rDispatch: Equipment3rDispatch) : Equipment3rRentalCase = withContext(Dispatchers.IO) {
        val localVarResponse = dispatchEquipment3rRentalCaseWithHttpInfo(caseId = caseId, equipment3rDispatch = equipment3rDispatch)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rRentalCase
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/dispatch
     * Record the carrier and vehicle dispatch leg for an approved Equipment 3R case
     *
     * @param caseId
     * @param equipment3rDispatch
     * @return ApiResponse<Equipment3rRentalCase?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun dispatchEquipment3rRentalCaseWithHttpInfo(caseId: java.util.UUID, equipment3rDispatch: Equipment3rDispatch) : ApiResponse<Equipment3rRentalCase?> = withContext(Dispatchers.IO) {
        val localVariableConfig = dispatchEquipment3rRentalCaseRequestConfig(caseId = caseId, equipment3rDispatch = equipment3rDispatch)

        return@withContext request<Equipment3rDispatch, Equipment3rRentalCase>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation dispatchEquipment3rRentalCase
     *
     * @param caseId
     * @param equipment3rDispatch
     * @return RequestConfig
     */
    fun dispatchEquipment3rRentalCaseRequestConfig(caseId: java.util.UUID, equipment3rDispatch: Equipment3rDispatch) : RequestConfig<Equipment3rDispatch> {
        val localVariableBody = equipment3rDispatch
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/rental-cases/{case_id}/dispatch".replace("{"+"case_id"+"}", encodeURIComponent(caseId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/equipment-3r/rental-cases/{case_id}
     * Read an Equipment 3R rental case and its evidence-bearing lifecycle detail
     *
     * @param caseId
     * @return Equipment3rRentalCaseDetail
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getEquipment3rRentalCase(caseId: java.util.UUID) : Equipment3rRentalCaseDetail = withContext(Dispatchers.IO) {
        val localVarResponse = getEquipment3rRentalCaseWithHttpInfo(caseId = caseId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rRentalCaseDetail
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/equipment-3r/rental-cases/{case_id}
     * Read an Equipment 3R rental case and its evidence-bearing lifecycle detail
     *
     * @param caseId
     * @return ApiResponse<Equipment3rRentalCaseDetail?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getEquipment3rRentalCaseWithHttpInfo(caseId: java.util.UUID) : ApiResponse<Equipment3rRentalCaseDetail?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getEquipment3rRentalCaseRequestConfig(caseId = caseId)

        return@withContext request<Unit, Equipment3rRentalCaseDetail>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getEquipment3rRentalCase
     *
     * @param caseId
     * @return RequestConfig
     */
    fun getEquipment3rRentalCaseRequestConfig(caseId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/equipment-3r/rental-cases/{case_id}".replace("{"+"case_id"+"}", encodeURIComponent(caseId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/equipment-3r/units/{unit_id}
     * Read an Equipment 3R unit with its active aggregate references
     *
     * @param unitId
     * @return Equipment3rUnitDetail
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getEquipment3rUnit(unitId: java.util.UUID) : Equipment3rUnitDetail = withContext(Dispatchers.IO) {
        val localVarResponse = getEquipment3rUnitWithHttpInfo(unitId = unitId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rUnitDetail
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/equipment-3r/units/{unit_id}
     * Read an Equipment 3R unit with its active aggregate references
     *
     * @param unitId
     * @return ApiResponse<Equipment3rUnitDetail?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getEquipment3rUnitWithHttpInfo(unitId: java.util.UUID) : ApiResponse<Equipment3rUnitDetail?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getEquipment3rUnitRequestConfig(unitId = unitId)

        return@withContext request<Unit, Equipment3rUnitDetail>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getEquipment3rUnit
     *
     * @param unitId
     * @return RequestConfig
     */
    fun getEquipment3rUnitRequestConfig(unitId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/equipment-3r/units/{unit_id}".replace("{"+"unit_id"+"}", encodeURIComponent(unitId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/handover
     * Record recipient and immutable evidence for an Equipment 3R handover
     *
     * @param caseId
     * @param equipment3rHandover
     * @return Equipment3rRentalCase
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun handoverEquipment3rRentalCase(caseId: java.util.UUID, equipment3rHandover: Equipment3rHandover) : Equipment3rRentalCase = withContext(Dispatchers.IO) {
        val localVarResponse = handoverEquipment3rRentalCaseWithHttpInfo(caseId = caseId, equipment3rHandover = equipment3rHandover)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rRentalCase
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/handover
     * Record recipient and immutable evidence for an Equipment 3R handover
     *
     * @param caseId
     * @param equipment3rHandover
     * @return ApiResponse<Equipment3rRentalCase?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun handoverEquipment3rRentalCaseWithHttpInfo(caseId: java.util.UUID, equipment3rHandover: Equipment3rHandover) : ApiResponse<Equipment3rRentalCase?> = withContext(Dispatchers.IO) {
        val localVariableConfig = handoverEquipment3rRentalCaseRequestConfig(caseId = caseId, equipment3rHandover = equipment3rHandover)

        return@withContext request<Equipment3rHandover, Equipment3rRentalCase>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation handoverEquipment3rRentalCase
     *
     * @param caseId
     * @param equipment3rHandover
     * @return RequestConfig
     */
    fun handoverEquipment3rRentalCaseRequestConfig(caseId: java.util.UUID, equipment3rHandover: Equipment3rHandover) : RequestConfig<Equipment3rHandover> {
        val localVariableBody = equipment3rHandover
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/rental-cases/{case_id}/handover".replace("{"+"case_id"+"}", encodeURIComponent(caseId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/inspections
     * Append an Equipment 3R inspection or maintenance record
     *
     * @param caseId
     * @param equipment3rInspectionRequest
     * @return Equipment3rInspection
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun inspectEquipment3rRentalCase(caseId: java.util.UUID, equipment3rInspectionRequest: Equipment3rInspectionRequest) : Equipment3rInspection = withContext(Dispatchers.IO) {
        val localVarResponse = inspectEquipment3rRentalCaseWithHttpInfo(caseId = caseId, equipment3rInspectionRequest = equipment3rInspectionRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rInspection
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/inspections
     * Append an Equipment 3R inspection or maintenance record
     *
     * @param caseId
     * @param equipment3rInspectionRequest
     * @return ApiResponse<Equipment3rInspection?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun inspectEquipment3rRentalCaseWithHttpInfo(caseId: java.util.UUID, equipment3rInspectionRequest: Equipment3rInspectionRequest) : ApiResponse<Equipment3rInspection?> = withContext(Dispatchers.IO) {
        val localVariableConfig = inspectEquipment3rRentalCaseRequestConfig(caseId = caseId, equipment3rInspectionRequest = equipment3rInspectionRequest)

        return@withContext request<Equipment3rInspectionRequest, Equipment3rInspection>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation inspectEquipment3rRentalCase
     *
     * @param caseId
     * @param equipment3rInspectionRequest
     * @return RequestConfig
     */
    fun inspectEquipment3rRentalCaseRequestConfig(caseId: java.util.UUID, equipment3rInspectionRequest: Equipment3rInspectionRequest) : RequestConfig<Equipment3rInspectionRequest> {
        val localVariableBody = equipment3rInspectionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/rental-cases/{case_id}/inspections".replace("{"+"case_id"+"}", encodeURIComponent(caseId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/equipment-3r/rental-cases
     * List the caller-visible Equipment 3R rental cases
     *
     * @return kotlin.collections.List<Equipment3rRentalCase>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listEquipment3rRentalCases() : kotlin.collections.List<Equipment3rRentalCase> = withContext(Dispatchers.IO) {
        val localVarResponse = listEquipment3rRentalCasesWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Equipment3rRentalCase>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/equipment-3r/rental-cases
     * List the caller-visible Equipment 3R rental cases
     *
     * @return ApiResponse<kotlin.collections.List<Equipment3rRentalCase>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listEquipment3rRentalCasesWithHttpInfo() : ApiResponse<kotlin.collections.List<Equipment3rRentalCase>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listEquipment3rRentalCasesRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<Equipment3rRentalCase>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listEquipment3rRentalCases
     *
     * @return RequestConfig
     */
    fun listEquipment3rRentalCasesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/equipment-3r/rental-cases",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/equipment-3r/units/{unit_id}/history
     * Read append-only Equipment 3R lifecycle history
     *
     * @param unitId
     * @return kotlin.collections.List<Equipment3rHistoryEntry>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listEquipment3rUnitHistory(unitId: java.util.UUID) : kotlin.collections.List<Equipment3rHistoryEntry> = withContext(Dispatchers.IO) {
        val localVarResponse = listEquipment3rUnitHistoryWithHttpInfo(unitId = unitId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Equipment3rHistoryEntry>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/equipment-3r/units/{unit_id}/history
     * Read append-only Equipment 3R lifecycle history
     *
     * @param unitId
     * @return ApiResponse<kotlin.collections.List<Equipment3rHistoryEntry>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listEquipment3rUnitHistoryWithHttpInfo(unitId: java.util.UUID) : ApiResponse<kotlin.collections.List<Equipment3rHistoryEntry>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listEquipment3rUnitHistoryRequestConfig(unitId = unitId)

        return@withContext request<Unit, kotlin.collections.List<Equipment3rHistoryEntry>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listEquipment3rUnitHistory
     *
     * @param unitId
     * @return RequestConfig
     */
    fun listEquipment3rUnitHistoryRequestConfig(unitId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/equipment-3r/units/{unit_id}/history".replace("{"+"unit_id"+"}", encodeURIComponent(unitId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/equipment-3r/units
     * List the caller-visible Equipment 3R units
     *
     * @return kotlin.collections.List<Equipment3rUnit>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listEquipment3rUnits() : kotlin.collections.List<Equipment3rUnit> = withContext(Dispatchers.IO) {
        val localVarResponse = listEquipment3rUnitsWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Equipment3rUnit>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/equipment-3r/units
     * List the caller-visible Equipment 3R units
     *
     * @return ApiResponse<kotlin.collections.List<Equipment3rUnit>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listEquipment3rUnitsWithHttpInfo() : ApiResponse<kotlin.collections.List<Equipment3rUnit>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listEquipment3rUnitsRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<Equipment3rUnit>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listEquipment3rUnits
     *
     * @return RequestConfig
     */
    fun listEquipment3rUnitsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/equipment-3r/units",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases
     * Create or idempotently replay an Equipment 3R rental quote
     *
     * @param idempotencyKey
     * @param equipment3rQuoteCase
     * @return Equipment3rRentalCase
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun quoteEquipment3rRentalCase(idempotencyKey: kotlin.String, equipment3rQuoteCase: Equipment3rQuoteCase) : Equipment3rRentalCase = withContext(Dispatchers.IO) {
        val localVarResponse = quoteEquipment3rRentalCaseWithHttpInfo(idempotencyKey = idempotencyKey, equipment3rQuoteCase = equipment3rQuoteCase)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rRentalCase
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases
     * Create or idempotently replay an Equipment 3R rental quote
     *
     * @param idempotencyKey
     * @param equipment3rQuoteCase
     * @return ApiResponse<Equipment3rRentalCase?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun quoteEquipment3rRentalCaseWithHttpInfo(idempotencyKey: kotlin.String, equipment3rQuoteCase: Equipment3rQuoteCase) : ApiResponse<Equipment3rRentalCase?> = withContext(Dispatchers.IO) {
        val localVariableConfig = quoteEquipment3rRentalCaseRequestConfig(idempotencyKey = idempotencyKey, equipment3rQuoteCase = equipment3rQuoteCase)

        return@withContext request<Equipment3rQuoteCase, Equipment3rRentalCase>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation quoteEquipment3rRentalCase
     *
     * @param idempotencyKey
     * @param equipment3rQuoteCase
     * @return RequestConfig
     */
    fun quoteEquipment3rRentalCaseRequestConfig(idempotencyKey: kotlin.String, equipment3rQuoteCase: Equipment3rQuoteCase) : RequestConfig<Equipment3rQuoteCase> {
        val localVariableBody = equipment3rQuoteCase
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/rental-cases",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/units
     * Register a serialized Equipment 3R unit
     *
     * @param equipment3rRegisterUnit
     * @return Equipment3rUnit
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun registerEquipment3rUnit(equipment3rRegisterUnit: Equipment3rRegisterUnit) : Equipment3rUnit = withContext(Dispatchers.IO) {
        val localVarResponse = registerEquipment3rUnitWithHttpInfo(equipment3rRegisterUnit = equipment3rRegisterUnit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rUnit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/units
     * Register a serialized Equipment 3R unit
     *
     * @param equipment3rRegisterUnit
     * @return ApiResponse<Equipment3rUnit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun registerEquipment3rUnitWithHttpInfo(equipment3rRegisterUnit: Equipment3rRegisterUnit) : ApiResponse<Equipment3rUnit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = registerEquipment3rUnitRequestConfig(equipment3rRegisterUnit = equipment3rRegisterUnit)

        return@withContext request<Equipment3rRegisterUnit, Equipment3rUnit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation registerEquipment3rUnit
     *
     * @param equipment3rRegisterUnit
     * @return RequestConfig
     */
    fun registerEquipment3rUnitRequestConfig(equipment3rRegisterUnit: Equipment3rRegisterUnit) : RequestConfig<Equipment3rRegisterUnit> {
        val localVariableBody = equipment3rRegisterUnit
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/units",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/return
     * Record physical return and move the unit to assessment
     *
     * @param caseId
     * @param equipment3rReturn
     * @return Equipment3rRentalCase
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun returnEquipment3rRentalCase(caseId: java.util.UUID, equipment3rReturn: Equipment3rReturn) : Equipment3rRentalCase = withContext(Dispatchers.IO) {
        val localVarResponse = returnEquipment3rRentalCaseWithHttpInfo(caseId = caseId, equipment3rReturn = equipment3rReturn)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Equipment3rRentalCase
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/equipment-3r/rental-cases/{case_id}/return
     * Record physical return and move the unit to assessment
     *
     * @param caseId
     * @param equipment3rReturn
     * @return ApiResponse<Equipment3rRentalCase?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun returnEquipment3rRentalCaseWithHttpInfo(caseId: java.util.UUID, equipment3rReturn: Equipment3rReturn) : ApiResponse<Equipment3rRentalCase?> = withContext(Dispatchers.IO) {
        val localVariableConfig = returnEquipment3rRentalCaseRequestConfig(caseId = caseId, equipment3rReturn = equipment3rReturn)

        return@withContext request<Equipment3rReturn, Equipment3rRentalCase>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation returnEquipment3rRentalCase
     *
     * @param caseId
     * @param equipment3rReturn
     * @return RequestConfig
     */
    fun returnEquipment3rRentalCaseRequestConfig(caseId: java.util.UUID, equipment3rReturn: Equipment3rReturn) : RequestConfig<Equipment3rReturn> {
        val localVariableBody = equipment3rReturn
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/equipment-3r/rental-cases/{case_id}/return".replace("{"+"case_id"+"}", encodeURIComponent(caseId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
