/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.CreateLeavePromotion
import com.maintenance.api.client.model.CreateLeaveRequest
import com.maintenance.api.client.model.DecideLeaveRequest
import com.maintenance.api.client.model.LeavePromotion
import com.maintenance.api.client.model.LeaveRequest
import com.maintenance.api.client.model.LeaveRequestPage
import com.maintenance.api.client.model.MyLeaveOverview

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class HRLeaveApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/hr/leave-promotions
     *
     *
     * @param createLeavePromotion
     * @return LeavePromotion
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createLeavePromotion(createLeavePromotion: CreateLeavePromotion) : LeavePromotion = withContext(Dispatchers.IO) {
        val localVarResponse = createLeavePromotionWithHttpInfo(createLeavePromotion = createLeavePromotion)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeavePromotion
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/leave-promotions
     *
     *
     * @param createLeavePromotion
     * @return ApiResponse<LeavePromotion?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createLeavePromotionWithHttpInfo(createLeavePromotion: CreateLeavePromotion) : ApiResponse<LeavePromotion?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createLeavePromotionRequestConfig(createLeavePromotion = createLeavePromotion)

        return@withContext request<CreateLeavePromotion, LeavePromotion>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createLeavePromotion
     *
     * @param createLeavePromotion
     * @return RequestConfig
     */
    fun createLeavePromotionRequestConfig(createLeavePromotion: CreateLeavePromotion) : RequestConfig<CreateLeavePromotion> {
        val localVariableBody = createLeavePromotion
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/leave-promotions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/leave-requests
     * File a leave request (owner self-service)
     *
     * @param createLeaveRequest
     * @return LeaveRequest
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createLeaveRequest(createLeaveRequest: CreateLeaveRequest) : LeaveRequest = withContext(Dispatchers.IO) {
        val localVarResponse = createLeaveRequestWithHttpInfo(createLeaveRequest = createLeaveRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveRequest
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/leave-requests
     * File a leave request (owner self-service)
     *
     * @param createLeaveRequest
     * @return ApiResponse<LeaveRequest?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createLeaveRequestWithHttpInfo(createLeaveRequest: CreateLeaveRequest) : ApiResponse<LeaveRequest?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createLeaveRequestRequestConfig(createLeaveRequest = createLeaveRequest)

        return@withContext request<CreateLeaveRequest, LeaveRequest>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createLeaveRequest
     *
     * @param createLeaveRequest
     * @return RequestConfig
     */
    fun createLeaveRequestRequestConfig(createLeaveRequest: CreateLeaveRequest) : RequestConfig<CreateLeaveRequest> {
        val localVariableBody = createLeaveRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/leave-requests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/leave-requests/{id}/decide
     *
     *
     * @param id
     * @param decideLeaveRequest
     * @return LeaveRequest
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun decideLeaveRequest(id: java.util.UUID, decideLeaveRequest: DecideLeaveRequest) : LeaveRequest = withContext(Dispatchers.IO) {
        val localVarResponse = decideLeaveRequestWithHttpInfo(id = id, decideLeaveRequest = decideLeaveRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveRequest
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/leave-requests/{id}/decide
     *
     *
     * @param id
     * @param decideLeaveRequest
     * @return ApiResponse<LeaveRequest?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun decideLeaveRequestWithHttpInfo(id: java.util.UUID, decideLeaveRequest: DecideLeaveRequest) : ApiResponse<LeaveRequest?> = withContext(Dispatchers.IO) {
        val localVariableConfig = decideLeaveRequestRequestConfig(id = id, decideLeaveRequest = decideLeaveRequest)

        return@withContext request<DecideLeaveRequest, LeaveRequest>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation decideLeaveRequest
     *
     * @param id
     * @param decideLeaveRequest
     * @return RequestConfig
     */
    fun decideLeaveRequestRequestConfig(id: java.util.UUID, decideLeaveRequest: DecideLeaveRequest) : RequestConfig<DecideLeaveRequest> {
        val localVariableBody = decideLeaveRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/leave-requests/{id}/decide".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/leave-promotions
     *
     *
     * @return kotlin.collections.List<LeavePromotion>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listLeavePromotions() : kotlin.collections.List<LeavePromotion> = withContext(Dispatchers.IO) {
        val localVarResponse = listLeavePromotionsWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<LeavePromotion>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/leave-promotions
     *
     *
     * @return ApiResponse<kotlin.collections.List<LeavePromotion>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listLeavePromotionsWithHttpInfo() : ApiResponse<kotlin.collections.List<LeavePromotion>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listLeavePromotionsRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<LeavePromotion>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listLeavePromotions
     *
     * @return RequestConfig
     */
    fun listLeavePromotionsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/leave-promotions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter status
     */
     enum class StatusListTeamLeaveRequests(val value: kotlin.String) {
         @SerialName(value = "all") ALL("all"),
         @SerialName(value = "DRAFT") DRAFT("DRAFT"),
         @SerialName(value = "SUBMITTED") SUBMITTED("SUBMITTED"),
         @SerialName(value = "APPROVED") APPROVED("APPROVED"),
         @SerialName(value = "REJECTED") REJECTED("REJECTED");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /api/v1/hr/leave-requests
     * Team leave-request queue (branch-scoped)
     *
     * @param status  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return LeaveRequestPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listTeamLeaveRequests(status: StatusListTeamLeaveRequests? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null) : LeaveRequestPage = withContext(Dispatchers.IO) {
        val localVarResponse = listTeamLeaveRequestsWithHttpInfo(status = status, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveRequestPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/leave-requests
     * Team leave-request queue (branch-scoped)
     *
     * @param status  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return ApiResponse<LeaveRequestPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listTeamLeaveRequestsWithHttpInfo(status: StatusListTeamLeaveRequests?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<LeaveRequestPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listTeamLeaveRequestsRequestConfig(status = status, limit = limit, offset = offset)

        return@withContext request<Unit, LeaveRequestPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listTeamLeaveRequests
     *
     * @param status  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return RequestConfig
     */
    fun listTeamLeaveRequestsRequestConfig(status: StatusListTeamLeaveRequests?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (status != null) {
                    put("status", listOf(status.value))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/leave-requests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/leave-requests/me
     * My leave balance and requests
     *
     * @return MyLeaveOverview
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun myLeaveOverview() : MyLeaveOverview = withContext(Dispatchers.IO) {
        val localVarResponse = myLeaveOverviewWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MyLeaveOverview
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/leave-requests/me
     * My leave balance and requests
     *
     * @return ApiResponse<MyLeaveOverview?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun myLeaveOverviewWithHttpInfo() : ApiResponse<MyLeaveOverview?> = withContext(Dispatchers.IO) {
        val localVariableConfig = myLeaveOverviewRequestConfig()

        return@withContext request<Unit, MyLeaveOverview>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation myLeaveOverview
     *
     * @return RequestConfig
     */
    fun myLeaveOverviewRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/leave-requests/me",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/leave-promotions/{id}/send
     *
     *
     * @param id
     * @return LeavePromotion
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun sendLeavePromotion(id: java.util.UUID) : LeavePromotion = withContext(Dispatchers.IO) {
        val localVarResponse = sendLeavePromotionWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeavePromotion
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/leave-promotions/{id}/send
     *
     *
     * @param id
     * @return ApiResponse<LeavePromotion?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun sendLeavePromotionWithHttpInfo(id: java.util.UUID) : ApiResponse<LeavePromotion?> = withContext(Dispatchers.IO) {
        val localVariableConfig = sendLeavePromotionRequestConfig(id = id)

        return@withContext request<Unit, LeavePromotion>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation sendLeavePromotion
     *
     * @param id
     * @return RequestConfig
     */
    fun sendLeavePromotionRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/leave-promotions/{id}/send".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
