/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.ConsumeInventoryItemRequest
import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.InventoryConsumptionEvent
import com.maintenance.api.client.model.InventoryConsumptionResult
import com.maintenance.api.client.model.InventoryItem
import com.maintenance.api.client.model.InventoryItemPage

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class InventoryApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/inventory/items/{item_id}/consumptions
     * Record an idempotent, non-negative inventory consumption
     *
     * @param itemId
     * @param consumeInventoryItemRequest
     * @return InventoryConsumptionResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun consumeInventoryItem(itemId: java.util.UUID, consumeInventoryItemRequest: ConsumeInventoryItemRequest) : InventoryConsumptionResult = withContext(Dispatchers.IO) {
        val localVarResponse = consumeInventoryItemWithHttpInfo(itemId = itemId, consumeInventoryItemRequest = consumeInventoryItemRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InventoryConsumptionResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/inventory/items/{item_id}/consumptions
     * Record an idempotent, non-negative inventory consumption
     *
     * @param itemId
     * @param consumeInventoryItemRequest
     * @return ApiResponse<InventoryConsumptionResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun consumeInventoryItemWithHttpInfo(itemId: java.util.UUID, consumeInventoryItemRequest: ConsumeInventoryItemRequest) : ApiResponse<InventoryConsumptionResult?> = withContext(Dispatchers.IO) {
        val localVariableConfig = consumeInventoryItemRequestConfig(itemId = itemId, consumeInventoryItemRequest = consumeInventoryItemRequest)

        return@withContext request<ConsumeInventoryItemRequest, InventoryConsumptionResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation consumeInventoryItem
     *
     * @param itemId
     * @param consumeInventoryItemRequest
     * @return RequestConfig
     */
    fun consumeInventoryItemRequestConfig(itemId: java.util.UUID, consumeInventoryItemRequest: ConsumeInventoryItemRequest) : RequestConfig<ConsumeInventoryItemRequest> {
        val localVariableBody = consumeInventoryItemRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/inventory/items/{item_id}/consumptions".replace("{"+"item_id"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/inventory/items/{item_id}
     * Get one tenant-authorized inventory item
     *
     * @param itemId
     * @return InventoryItem
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getInventoryItem(itemId: java.util.UUID) : InventoryItem = withContext(Dispatchers.IO) {
        val localVarResponse = getInventoryItemWithHttpInfo(itemId = itemId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InventoryItem
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/inventory/items/{item_id}
     * Get one tenant-authorized inventory item
     *
     * @param itemId
     * @return ApiResponse<InventoryItem?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getInventoryItemWithHttpInfo(itemId: java.util.UUID) : ApiResponse<InventoryItem?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getInventoryItemRequestConfig(itemId = itemId)

        return@withContext request<Unit, InventoryItem>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getInventoryItem
     *
     * @param itemId
     * @return RequestConfig
     */
    fun getInventoryItemRequestConfig(itemId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/inventory/items/{item_id}".replace("{"+"item_id"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/inventory/items/{item_id}/consumptions
     * List immutable item-consumption events
     *
     * @param itemId
     * @param sourceKind  (optional)
     * @param workOrderId  (optional)
     * @param dispatchId  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return kotlin.collections.List<InventoryConsumptionEvent>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listInventoryConsumptions(itemId: java.util.UUID, sourceKind: kotlin.String? = null, workOrderId: java.util.UUID? = null, dispatchId: java.util.UUID? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null) : kotlin.collections.List<InventoryConsumptionEvent> = withContext(Dispatchers.IO) {
        val localVarResponse = listInventoryConsumptionsWithHttpInfo(itemId = itemId, sourceKind = sourceKind, workOrderId = workOrderId, dispatchId = dispatchId, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<InventoryConsumptionEvent>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/inventory/items/{item_id}/consumptions
     * List immutable item-consumption events
     *
     * @param itemId
     * @param sourceKind  (optional)
     * @param workOrderId  (optional)
     * @param dispatchId  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return ApiResponse<kotlin.collections.List<InventoryConsumptionEvent>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listInventoryConsumptionsWithHttpInfo(itemId: java.util.UUID, sourceKind: kotlin.String?, workOrderId: java.util.UUID?, dispatchId: java.util.UUID?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<kotlin.collections.List<InventoryConsumptionEvent>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listInventoryConsumptionsRequestConfig(itemId = itemId, sourceKind = sourceKind, workOrderId = workOrderId, dispatchId = dispatchId, limit = limit, offset = offset)

        return@withContext request<Unit, kotlin.collections.List<InventoryConsumptionEvent>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listInventoryConsumptions
     *
     * @param itemId
     * @param sourceKind  (optional)
     * @param workOrderId  (optional)
     * @param dispatchId  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return RequestConfig
     */
    fun listInventoryConsumptionsRequestConfig(itemId: java.util.UUID, sourceKind: kotlin.String?, workOrderId: java.util.UUID?, dispatchId: java.util.UUID?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (sourceKind != null) {
                    put("source_kind", listOf(sourceKind.toString()))
                }
                if (workOrderId != null) {
                    put("work_order_id", listOf(workOrderId.toString()))
                }
                if (dispatchId != null) {
                    put("dispatch_id", listOf(dispatchId.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/inventory/items/{item_id}/consumptions".replace("{"+"item_id"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/inventory/items
     * List tenant-scoped inventory items
     *
     * @param branchId  (optional)
     * @param siteId  (optional)
     * @param stockLocationId  (optional)
     * @param status  (optional)
     * @param lowStock  (optional)
     * @param q  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return InventoryItemPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listInventoryItems(branchId: java.util.UUID? = null, siteId: java.util.UUID? = null, stockLocationId: java.util.UUID? = null, status: kotlin.String? = null, lowStock: kotlin.Boolean? = null, q: kotlin.String? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null) : InventoryItemPage = withContext(Dispatchers.IO) {
        val localVarResponse = listInventoryItemsWithHttpInfo(branchId = branchId, siteId = siteId, stockLocationId = stockLocationId, status = status, lowStock = lowStock, q = q, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InventoryItemPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/inventory/items
     * List tenant-scoped inventory items
     *
     * @param branchId  (optional)
     * @param siteId  (optional)
     * @param stockLocationId  (optional)
     * @param status  (optional)
     * @param lowStock  (optional)
     * @param q  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return ApiResponse<InventoryItemPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listInventoryItemsWithHttpInfo(branchId: java.util.UUID?, siteId: java.util.UUID?, stockLocationId: java.util.UUID?, status: kotlin.String?, lowStock: kotlin.Boolean?, q: kotlin.String?, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<InventoryItemPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listInventoryItemsRequestConfig(branchId = branchId, siteId = siteId, stockLocationId = stockLocationId, status = status, lowStock = lowStock, q = q, limit = limit, offset = offset)

        return@withContext request<Unit, InventoryItemPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listInventoryItems
     *
     * @param branchId  (optional)
     * @param siteId  (optional)
     * @param stockLocationId  (optional)
     * @param status  (optional)
     * @param lowStock  (optional)
     * @param q  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return RequestConfig
     */
    fun listInventoryItemsRequestConfig(branchId: java.util.UUID?, siteId: java.util.UUID?, stockLocationId: java.util.UUID?, status: kotlin.String?, lowStock: kotlin.Boolean?, q: kotlin.String?, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (branchId != null) {
                    put("branch_id", listOf(branchId.toString()))
                }
                if (siteId != null) {
                    put("site_id", listOf(siteId.toString()))
                }
                if (stockLocationId != null) {
                    put("stock_location_id", listOf(stockLocationId.toString()))
                }
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
                if (lowStock != null) {
                    put("low_stock", listOf(lowStock.toString()))
                }
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/inventory/items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
