/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.LeaveChargeResolutionRequest
import com.maintenance.api.client.model.LeaveChargeResolutionView
import com.maintenance.api.client.model.LeaveCreateRequest
import com.maintenance.api.client.model.LeaveDecideRequest
import com.maintenance.api.client.model.LeavePromotionRequest
import com.maintenance.api.client.model.LeaveRefusalRequest
import com.maintenance.api.client.model.LeaveRequestPage
import com.maintenance.api.client.model.LeaveRequestView
import com.maintenance.api.client.model.LeaveRosterPage
import com.maintenance.api.client.model.LeaveStatutoryPushView
import com.maintenance.api.client.model.MyLeaveOverview

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class LeaveApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/leave/requests
     * File a self-service 연차/반차 request (본인 연차 신청)
     * The caller files a leave request for THEMSELVES. &#x60;subject_employee_id&#x60; and the routing &#x60;branch_id&#x60; are resolved server-side from the caller&#39;s own account and employee.home_branch_id — never from input — so a caller can only file for their own employee record. No directory feature is required (filing one&#39;s own leave is a base employee capability); the gate is an active account linked to an active employee; an unlinked or inactive subject is denied with 403. Missing home-branch authority returns the stable 409 &#x60;leave_home_branch_review_required&#x60;. The request preserves date and AM/PM intent in &#x60;review_required&#x60;; no calendar-day or fixed-half quantity is invented. A separate resolver pins authoritative evidence before any approval can move the ledger.
     * @param leaveCreateRequest
     * @return LeaveRequestView
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createLeaveRequest(leaveCreateRequest: LeaveCreateRequest) : LeaveRequestView = withContext(Dispatchers.IO) {
        val localVarResponse = createLeaveRequestWithHttpInfo(leaveCreateRequest = leaveCreateRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveRequestView
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/leave/requests
     * File a self-service 연차/반차 request (본인 연차 신청)
     * The caller files a leave request for THEMSELVES. &#x60;subject_employee_id&#x60; and the routing &#x60;branch_id&#x60; are resolved server-side from the caller&#39;s own account and employee.home_branch_id — never from input — so a caller can only file for their own employee record. No directory feature is required (filing one&#39;s own leave is a base employee capability); the gate is an active account linked to an active employee; an unlinked or inactive subject is denied with 403. Missing home-branch authority returns the stable 409 &#x60;leave_home_branch_review_required&#x60;. The request preserves date and AM/PM intent in &#x60;review_required&#x60;; no calendar-day or fixed-half quantity is invented. A separate resolver pins authoritative evidence before any approval can move the ledger.
     * @param leaveCreateRequest
     * @return ApiResponse<LeaveRequestView?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createLeaveRequestWithHttpInfo(leaveCreateRequest: LeaveCreateRequest) : ApiResponse<LeaveRequestView?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createLeaveRequestRequestConfig(leaveCreateRequest = leaveCreateRequest)

        return@withContext request<LeaveCreateRequest, LeaveRequestView>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createLeaveRequest
     *
     * @param leaveCreateRequest
     * @return RequestConfig
     */
    fun createLeaveRequestRequestConfig(leaveCreateRequest: LeaveCreateRequest) : RequestConfig<LeaveCreateRequest> {
        val localVariableBody = leaveCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/leave/requests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/leave/requests/{id}/decide
     * Approve, return, or reject a pending leave request
     * Requires &#x60;employee_directory_manage&#x60; in the request&#39;s branch. An APPROVE writes the leave ledger (used +&#x3D; exact resolved charge units, remaining -&#x3D; exact resolved charge units) in the same audited transaction. Separation of duties — a request cannot be decided by its own requester (403). &#x60;return&#x60;/&#x60;reject&#x60; require a comment. Approval additionally requires a resolved exact charge and a distinct resolver. The body must carry the current request_version as &#x60;expected_version&#x60;; charge_version identifies immutable evidence and is never a request mutation precondition. A successful decision increments request_version only; charge_version remains unchanged. An unresolved approval returns 409 &#x60;leave_calendar_review_required&#x60; plus review reasons, audits the blocked attempt, and changes neither request nor ledger.
     * @param id
     * @param leaveDecideRequest
     * @return LeaveRequestView
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun decideLeaveRequest(id: java.util.UUID, leaveDecideRequest: LeaveDecideRequest) : LeaveRequestView = withContext(Dispatchers.IO) {
        val localVarResponse = decideLeaveRequestWithHttpInfo(id = id, leaveDecideRequest = leaveDecideRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveRequestView
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/leave/requests/{id}/decide
     * Approve, return, or reject a pending leave request
     * Requires &#x60;employee_directory_manage&#x60; in the request&#39;s branch. An APPROVE writes the leave ledger (used +&#x3D; exact resolved charge units, remaining -&#x3D; exact resolved charge units) in the same audited transaction. Separation of duties — a request cannot be decided by its own requester (403). &#x60;return&#x60;/&#x60;reject&#x60; require a comment. Approval additionally requires a resolved exact charge and a distinct resolver. The body must carry the current request_version as &#x60;expected_version&#x60;; charge_version identifies immutable evidence and is never a request mutation precondition. A successful decision increments request_version only; charge_version remains unchanged. An unresolved approval returns 409 &#x60;leave_calendar_review_required&#x60; plus review reasons, audits the blocked attempt, and changes neither request nor ledger.
     * @param id
     * @param leaveDecideRequest
     * @return ApiResponse<LeaveRequestView?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun decideLeaveRequestWithHttpInfo(id: java.util.UUID, leaveDecideRequest: LeaveDecideRequest) : ApiResponse<LeaveRequestView?> = withContext(Dispatchers.IO) {
        val localVariableConfig = decideLeaveRequestRequestConfig(id = id, leaveDecideRequest = leaveDecideRequest)

        return@withContext request<LeaveDecideRequest, LeaveRequestView>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation decideLeaveRequest
     *
     * @param id
     * @param leaveDecideRequest
     * @return RequestConfig
     */
    fun decideLeaveRequestRequestConfig(id: java.util.UUID, leaveDecideRequest: LeaveDecideRequest) : RequestConfig<LeaveDecideRequest> {
        val localVariableBody = leaveDecideRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/leave/requests/{id}/decide".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/me/leave
     * Read the authenticated employee&#39;s own leave balance and history
     * Base employee self-service. The server binds both user and linked employee identity; no employee-directory feature is required and no employee or branch identifier is accepted from the client. The balance includes a closed filing state so a missing or inactive home branch is visible before submission rather than discovered only after a 409.
     * @param limit  (optional, default to 100L)
     * @return MyLeaveOverview
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getMyLeave(limit: kotlin.Long? = 100L) : MyLeaveOverview = withContext(Dispatchers.IO) {
        val localVarResponse = getMyLeaveWithHttpInfo(limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MyLeaveOverview
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/me/leave
     * Read the authenticated employee&#39;s own leave balance and history
     * Base employee self-service. The server binds both user and linked employee identity; no employee-directory feature is required and no employee or branch identifier is accepted from the client. The balance includes a closed filing state so a missing or inactive home branch is visible before submission rather than discovered only after a 409.
     * @param limit  (optional, default to 100L)
     * @return ApiResponse<MyLeaveOverview?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getMyLeaveWithHttpInfo(limit: kotlin.Long?) : ApiResponse<MyLeaveOverview?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getMyLeaveRequestConfig(limit = limit)

        return@withContext request<Unit, MyLeaveOverview>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMyLeave
     *
     * @param limit  (optional, default to 100L)
     * @return RequestConfig
     */
    fun getMyLeaveRequestConfig(limit: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/me/leave",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/leave/balances
     * Per-employee annual-leave balance roster (직원별 연차 현황)
     * Reads the existing employee leave ledger (grant/used/left) — the same source of truth as the balances aggregate; not a second store. Requires &#x60;employee_directory_read&#x60;. Org-scoped.
     * @return LeaveRosterPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listLeaveBalances() : LeaveRosterPage = withContext(Dispatchers.IO) {
        val localVarResponse = listLeaveBalancesWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveRosterPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/leave/balances
     * Per-employee annual-leave balance roster (직원별 연차 현황)
     * Reads the existing employee leave ledger (grant/used/left) — the same source of truth as the balances aggregate; not a second store. Requires &#x60;employee_directory_read&#x60;. Org-scoped.
     * @return ApiResponse<LeaveRosterPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listLeaveBalancesWithHttpInfo() : ApiResponse<LeaveRosterPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listLeaveBalancesRequestConfig()

        return@withContext request<Unit, LeaveRosterPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listLeaveBalances
     *
     * @return RequestConfig
     */
    fun listLeaveBalancesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/leave/balances",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter status
     */
     enum class StatusListLeaveRequests(val value: kotlin.String) {
         @SerialName(value = "pending") PENDING("pending"),
         @SerialName(value = "approved") APPROVED("approved"),
         @SerialName(value = "returned") RETURNED("returned"),
         @SerialName(value = "rejected") REJECTED("rejected");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /api/v1/leave/requests
     * List the branch-scoped leave-request approval queue (연차 결재함)
     * Pending-first, then newest. Requires &#x60;employee_directory_read&#x60;. The queue is confined to the caller&#39;s branches (resolved from the JWT); an out-of-scope request is invisible (deny-by-omission).
     * @param status Filter to one status; omitted returns all four. (optional)
     * @param limit Page size (clamped server-side to 1..&#x3D;200; default 100). (optional)
     * @return LeaveRequestPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listLeaveRequests(status: StatusListLeaveRequests? = null, limit: kotlin.Long? = null) : LeaveRequestPage = withContext(Dispatchers.IO) {
        val localVarResponse = listLeaveRequestsWithHttpInfo(status = status, limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveRequestPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/leave/requests
     * List the branch-scoped leave-request approval queue (연차 결재함)
     * Pending-first, then newest. Requires &#x60;employee_directory_read&#x60;. The queue is confined to the caller&#39;s branches (resolved from the JWT); an out-of-scope request is invisible (deny-by-omission).
     * @param status Filter to one status; omitted returns all four. (optional)
     * @param limit Page size (clamped server-side to 1..&#x3D;200; default 100). (optional)
     * @return ApiResponse<LeaveRequestPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listLeaveRequestsWithHttpInfo(status: StatusListLeaveRequests?, limit: kotlin.Long?) : ApiResponse<LeaveRequestPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listLeaveRequestsRequestConfig(status = status, limit = limit)

        return@withContext request<Unit, LeaveRequestPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listLeaveRequests
     *
     * @param status Filter to one status; omitted returns all four. (optional)
     * @param limit Page size (clamped server-side to 1..&#x3D;200; default 100). (optional)
     * @return RequestConfig
     */
    fun listLeaveRequestsRequestConfig(status: StatusListLeaveRequests?, limit: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (status != null) {
                    put("status", listOf(status.value))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/leave/requests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/leave/promotions
     * Serve a §61 연차 사용 촉진 (round 1 or 2)
     * Requires &#x60;employee_directory_manage&#x60; in the target &#x60;branch_id&#x60; (which is validated against the actor&#39;s scope). Delivers a receipt-gated 연차촉진 notice into the target&#39;s 개인 수신함 and records the push. The engine AP- run binds once the 연차촉진 submittable definition exists; until then the push carries &#x60;ap_submission: pending_engine_definition&#x60;. Idempotent per (target, round).
     * @param leavePromotionRequest
     * @return LeaveStatutoryPushView
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun pushLeavePromotion(leavePromotionRequest: LeavePromotionRequest) : LeaveStatutoryPushView = withContext(Dispatchers.IO) {
        val localVarResponse = pushLeavePromotionWithHttpInfo(leavePromotionRequest = leavePromotionRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveStatutoryPushView
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/leave/promotions
     * Serve a §61 연차 사용 촉진 (round 1 or 2)
     * Requires &#x60;employee_directory_manage&#x60; in the target &#x60;branch_id&#x60; (which is validated against the actor&#39;s scope). Delivers a receipt-gated 연차촉진 notice into the target&#39;s 개인 수신함 and records the push. The engine AP- run binds once the 연차촉진 submittable definition exists; until then the push carries &#x60;ap_submission: pending_engine_definition&#x60;. Idempotent per (target, round).
     * @param leavePromotionRequest
     * @return ApiResponse<LeaveStatutoryPushView?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun pushLeavePromotionWithHttpInfo(leavePromotionRequest: LeavePromotionRequest) : ApiResponse<LeaveStatutoryPushView?> = withContext(Dispatchers.IO) {
        val localVariableConfig = pushLeavePromotionRequestConfig(leavePromotionRequest = leavePromotionRequest)

        return@withContext request<LeavePromotionRequest, LeaveStatutoryPushView>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pushLeavePromotion
     *
     * @param leavePromotionRequest
     * @return RequestConfig
     */
    fun pushLeavePromotionRequestConfig(leavePromotionRequest: LeavePromotionRequest) : RequestConfig<LeavePromotionRequest> {
        val localVariableBody = leavePromotionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/leave/promotions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/leave/refusal-notices
     * Serve a 노무수령거부 notice (after a round-2 promotion)
     * Requires &#x60;employee_directory_manage&#x60; in the target &#x60;branch_id&#x60;. Delivers a receipt-gated 노무수령거부 notice into the target&#39;s 개인 수신함 and records the push. Same engine-binding semantics as promotions. Idempotent per target.
     * @param leaveRefusalRequest
     * @return LeaveStatutoryPushView
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun pushLeaveRefusalNotice(leaveRefusalRequest: LeaveRefusalRequest) : LeaveStatutoryPushView = withContext(Dispatchers.IO) {
        val localVarResponse = pushLeaveRefusalNoticeWithHttpInfo(leaveRefusalRequest = leaveRefusalRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveStatutoryPushView
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/leave/refusal-notices
     * Serve a 노무수령거부 notice (after a round-2 promotion)
     * Requires &#x60;employee_directory_manage&#x60; in the target &#x60;branch_id&#x60;. Delivers a receipt-gated 노무수령거부 notice into the target&#39;s 개인 수신함 and records the push. Same engine-binding semantics as promotions. Idempotent per target.
     * @param leaveRefusalRequest
     * @return ApiResponse<LeaveStatutoryPushView?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun pushLeaveRefusalNoticeWithHttpInfo(leaveRefusalRequest: LeaveRefusalRequest) : ApiResponse<LeaveStatutoryPushView?> = withContext(Dispatchers.IO) {
        val localVariableConfig = pushLeaveRefusalNoticeRequestConfig(leaveRefusalRequest = leaveRefusalRequest)

        return@withContext request<LeaveRefusalRequest, LeaveStatutoryPushView>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pushLeaveRefusalNotice
     *
     * @param leaveRefusalRequest
     * @return RequestConfig
     */
    fun pushLeaveRefusalNoticeRequestConfig(leaveRefusalRequest: LeaveRefusalRequest) : RequestConfig<LeaveRefusalRequest> {
        val localVariableBody = leaveRefusalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/leave/refusal-notices",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/leave/requests/{id}/charge-resolution
     * Record an audited exact leave-charge resolution
     * Requires EmployeeDirectoryManage in the request branch. The body carries reviewed per-date obligations and source revision references, never a client total or digest. The server validates complete date coverage, canonicalizes, totals, hashes, and records an immutable resolution. &#x60;expected_version&#x60; is the current mutable request_version; the charge_version is assigned independently to the evidence snapshot.
     * @param id
     * @param leaveChargeResolutionRequest
     * @return LeaveChargeResolutionView
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun resolveLeaveCharge(id: java.util.UUID, leaveChargeResolutionRequest: LeaveChargeResolutionRequest) : LeaveChargeResolutionView = withContext(Dispatchers.IO) {
        val localVarResponse = resolveLeaveChargeWithHttpInfo(id = id, leaveChargeResolutionRequest = leaveChargeResolutionRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveChargeResolutionView
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/leave/requests/{id}/charge-resolution
     * Record an audited exact leave-charge resolution
     * Requires EmployeeDirectoryManage in the request branch. The body carries reviewed per-date obligations and source revision references, never a client total or digest. The server validates complete date coverage, canonicalizes, totals, hashes, and records an immutable resolution. &#x60;expected_version&#x60; is the current mutable request_version; the charge_version is assigned independently to the evidence snapshot.
     * @param id
     * @param leaveChargeResolutionRequest
     * @return ApiResponse<LeaveChargeResolutionView?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun resolveLeaveChargeWithHttpInfo(id: java.util.UUID, leaveChargeResolutionRequest: LeaveChargeResolutionRequest) : ApiResponse<LeaveChargeResolutionView?> = withContext(Dispatchers.IO) {
        val localVariableConfig = resolveLeaveChargeRequestConfig(id = id, leaveChargeResolutionRequest = leaveChargeResolutionRequest)

        return@withContext request<LeaveChargeResolutionRequest, LeaveChargeResolutionView>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation resolveLeaveCharge
     *
     * @param id
     * @param leaveChargeResolutionRequest
     * @return RequestConfig
     */
    fun resolveLeaveChargeRequestConfig(id: java.util.UUID, leaveChargeResolutionRequest: LeaveChargeResolutionRequest) : RequestConfig<LeaveChargeResolutionRequest> {
        val localVariableBody = leaveChargeResolutionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/leave/requests/{id}/charge-resolution".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
