/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.CreateLogisticsAsnRequest
import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.PutawayLogisticsAsnRequest
import com.maintenance.api.client.model.ReceiveLogisticsAsnRequest
import com.maintenance.api.client.model.ReleaseLogisticsFulfillmentRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class LogisticsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/logistics/asns
     * Create a pilot ASN for one branch warehouse
     *
     * @param createLogisticsAsnRequest
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createLogisticsAsn(createLogisticsAsnRequest: CreateLogisticsAsnRequest) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = createLogisticsAsnWithHttpInfo(createLogisticsAsnRequest = createLogisticsAsnRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/asns
     * Create a pilot ASN for one branch warehouse
     *
     * @param createLogisticsAsnRequest
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createLogisticsAsnWithHttpInfo(createLogisticsAsnRequest: CreateLogisticsAsnRequest) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createLogisticsAsnRequestConfig(createLogisticsAsnRequest = createLogisticsAsnRequest)

        return@withContext request<CreateLogisticsAsnRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createLogisticsAsn
     *
     * @param createLogisticsAsnRequest
     * @return RequestConfig
     */
    fun createLogisticsAsnRequestConfig(createLogisticsAsnRequest: CreateLogisticsAsnRequest) : RequestConfig<CreateLogisticsAsnRequest> {
        val localVariableBody = createLogisticsAsnRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/asns",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/fulfillments/{fulfillment_id}/dispatch
     * Dispatch one packed carrier and vehicle leg
     *
     * @param fulfillmentId
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun dispatchLogisticsShipment(fulfillmentId: java.util.UUID) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = dispatchLogisticsShipmentWithHttpInfo(fulfillmentId = fulfillmentId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/fulfillments/{fulfillment_id}/dispatch
     * Dispatch one packed carrier and vehicle leg
     *
     * @param fulfillmentId
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun dispatchLogisticsShipmentWithHttpInfo(fulfillmentId: java.util.UUID) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = dispatchLogisticsShipmentRequestConfig(fulfillmentId = fulfillmentId)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation dispatchLogisticsShipment
     *
     * @param fulfillmentId
     * @return RequestConfig
     */
    fun dispatchLogisticsShipmentRequestConfig(fulfillmentId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/fulfillments/{fulfillment_id}/dispatch".replace("{"+"fulfillment_id"+"}", encodeURIComponent(fulfillmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/fulfillments/{fulfillment_id}/pack
     * Pack a picked or short-picked fulfillment
     *
     * @param fulfillmentId
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun packLogisticsFulfillment(fulfillmentId: java.util.UUID) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = packLogisticsFulfillmentWithHttpInfo(fulfillmentId = fulfillmentId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/fulfillments/{fulfillment_id}/pack
     * Pack a picked or short-picked fulfillment
     *
     * @param fulfillmentId
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun packLogisticsFulfillmentWithHttpInfo(fulfillmentId: java.util.UUID) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = packLogisticsFulfillmentRequestConfig(fulfillmentId = fulfillmentId)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation packLogisticsFulfillment
     *
     * @param fulfillmentId
     * @return RequestConfig
     */
    fun packLogisticsFulfillmentRequestConfig(fulfillmentId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/fulfillments/{fulfillment_id}/pack".replace("{"+"fulfillment_id"+"}", encodeURIComponent(fulfillmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/fulfillments/{fulfillment_id}/pick
     * Pick reserved stock, recording explicit short-pick when applicable
     *
     * @param fulfillmentId
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun pickLogisticsFulfillment(fulfillmentId: java.util.UUID) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = pickLogisticsFulfillmentWithHttpInfo(fulfillmentId = fulfillmentId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/fulfillments/{fulfillment_id}/pick
     * Pick reserved stock, recording explicit short-pick when applicable
     *
     * @param fulfillmentId
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun pickLogisticsFulfillmentWithHttpInfo(fulfillmentId: java.util.UUID) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = pickLogisticsFulfillmentRequestConfig(fulfillmentId = fulfillmentId)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pickLogisticsFulfillment
     *
     * @param fulfillmentId
     * @return RequestConfig
     */
    fun pickLogisticsFulfillmentRequestConfig(fulfillmentId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/fulfillments/{fulfillment_id}/pick".replace("{"+"fulfillment_id"+"}", encodeURIComponent(fulfillmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/asns/{asn_id}/putaway
     * Put received stock away into the pilot warehouse
     *
     * @param asnId
     * @param putawayLogisticsAsnRequest
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun putawayLogisticsAsn(asnId: java.util.UUID, putawayLogisticsAsnRequest: PutawayLogisticsAsnRequest) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = putawayLogisticsAsnWithHttpInfo(asnId = asnId, putawayLogisticsAsnRequest = putawayLogisticsAsnRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/asns/{asn_id}/putaway
     * Put received stock away into the pilot warehouse
     *
     * @param asnId
     * @param putawayLogisticsAsnRequest
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun putawayLogisticsAsnWithHttpInfo(asnId: java.util.UUID, putawayLogisticsAsnRequest: PutawayLogisticsAsnRequest) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = putawayLogisticsAsnRequestConfig(asnId = asnId, putawayLogisticsAsnRequest = putawayLogisticsAsnRequest)

        return@withContext request<PutawayLogisticsAsnRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation putawayLogisticsAsn
     *
     * @param asnId
     * @param putawayLogisticsAsnRequest
     * @return RequestConfig
     */
    fun putawayLogisticsAsnRequestConfig(asnId: java.util.UUID, putawayLogisticsAsnRequest: PutawayLogisticsAsnRequest) : RequestConfig<PutawayLogisticsAsnRequest> {
        val localVariableBody = putawayLogisticsAsnRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/asns/{asn_id}/putaway".replace("{"+"asn_id"+"}", encodeURIComponent(asnId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/asns/{asn_id}/receipts
     * Record an idempotent full or partial receipt; over-receipt is rejected
     *
     * @param asnId
     * @param idempotencyKey
     * @param receiveLogisticsAsnRequest
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun receiveLogisticsAsn(asnId: java.util.UUID, idempotencyKey: kotlin.String, receiveLogisticsAsnRequest: ReceiveLogisticsAsnRequest) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = receiveLogisticsAsnWithHttpInfo(asnId = asnId, idempotencyKey = idempotencyKey, receiveLogisticsAsnRequest = receiveLogisticsAsnRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/asns/{asn_id}/receipts
     * Record an idempotent full or partial receipt; over-receipt is rejected
     *
     * @param asnId
     * @param idempotencyKey
     * @param receiveLogisticsAsnRequest
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun receiveLogisticsAsnWithHttpInfo(asnId: java.util.UUID, idempotencyKey: kotlin.String, receiveLogisticsAsnRequest: ReceiveLogisticsAsnRequest) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = receiveLogisticsAsnRequestConfig(asnId = asnId, idempotencyKey = idempotencyKey, receiveLogisticsAsnRequest = receiveLogisticsAsnRequest)

        return@withContext request<ReceiveLogisticsAsnRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation receiveLogisticsAsn
     *
     * @param asnId
     * @param idempotencyKey
     * @param receiveLogisticsAsnRequest
     * @return RequestConfig
     */
    fun receiveLogisticsAsnRequestConfig(asnId: java.util.UUID, idempotencyKey: kotlin.String, receiveLogisticsAsnRequest: ReceiveLogisticsAsnRequest) : RequestConfig<ReceiveLogisticsAsnRequest> {
        val localVariableBody = receiveLogisticsAsnRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/asns/{asn_id}/receipts".replace("{"+"asn_id"+"}", encodeURIComponent(asnId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/fulfillments
     * Atomically reserve available pilot stock; never oversells
     *
     * @param releaseLogisticsFulfillmentRequest
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun releaseLogisticsFulfillment(releaseLogisticsFulfillmentRequest: ReleaseLogisticsFulfillmentRequest) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = releaseLogisticsFulfillmentWithHttpInfo(releaseLogisticsFulfillmentRequest = releaseLogisticsFulfillmentRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/fulfillments
     * Atomically reserve available pilot stock; never oversells
     *
     * @param releaseLogisticsFulfillmentRequest
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun releaseLogisticsFulfillmentWithHttpInfo(releaseLogisticsFulfillmentRequest: ReleaseLogisticsFulfillmentRequest) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = releaseLogisticsFulfillmentRequestConfig(releaseLogisticsFulfillmentRequest = releaseLogisticsFulfillmentRequest)

        return@withContext request<ReleaseLogisticsFulfillmentRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation releaseLogisticsFulfillment
     *
     * @param releaseLogisticsFulfillmentRequest
     * @return RequestConfig
     */
    fun releaseLogisticsFulfillmentRequestConfig(releaseLogisticsFulfillmentRequest: ReleaseLogisticsFulfillmentRequest) : RequestConfig<ReleaseLogisticsFulfillmentRequest> {
        val localVariableBody = releaseLogisticsFulfillmentRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/fulfillments",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/shipments/{shipment_id}/settlements
     * Settle one KRW operational transport cost; no finance or GL posting
     *
     * @param shipmentId
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun settleLogisticsOperationalCost(shipmentId: java.util.UUID) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = settleLogisticsOperationalCostWithHttpInfo(shipmentId = shipmentId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/shipments/{shipment_id}/settlements
     * Settle one KRW operational transport cost; no finance or GL posting
     *
     * @param shipmentId
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun settleLogisticsOperationalCostWithHttpInfo(shipmentId: java.util.UUID) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = settleLogisticsOperationalCostRequestConfig(shipmentId = shipmentId)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation settleLogisticsOperationalCost
     *
     * @param shipmentId
     * @return RequestConfig
     */
    fun settleLogisticsOperationalCostRequestConfig(shipmentId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/shipments/{shipment_id}/settlements".replace("{"+"shipment_id"+"}", encodeURIComponent(shipmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/logistics/shipments/{shipment_id}/pod
     * Verify recipient-confirmed immutable evidence and derive calendar-time SLA
     *
     * @param shipmentId
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun verifyLogisticsPod(shipmentId: java.util.UUID) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = verifyLogisticsPodWithHttpInfo(shipmentId = shipmentId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/logistics/shipments/{shipment_id}/pod
     * Verify recipient-confirmed immutable evidence and derive calendar-time SLA
     *
     * @param shipmentId
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun verifyLogisticsPodWithHttpInfo(shipmentId: java.util.UUID) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = verifyLogisticsPodRequestConfig(shipmentId = shipmentId)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation verifyLogisticsPod
     *
     * @param shipmentId
     * @return RequestConfig
     */
    fun verifyLogisticsPodRequestConfig(shipmentId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/logistics/shipments/{shipment_id}/pod".replace("{"+"shipment_id"+"}", encodeURIComponent(shipmentId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
