/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.MessengerAckSummary
import com.maintenance.api.client.model.MessengerPresenceListResponse
import com.maintenance.api.client.model.MessengerThreadListResponse
import com.maintenance.api.client.model.MessengerThreadSummary
import com.maintenance.api.client.model.SetMessengerThreadMuteRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class MessengerApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/messenger/threads/{threadId}/join
     * Join a channel-visibility thread in scope (idempotent)
     *
     * @param threadId
     * @return MessengerThreadSummary
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun joinMessengerThread(threadId: java.util.UUID) : MessengerThreadSummary = withContext(Dispatchers.IO) {
        val localVarResponse = joinMessengerThreadWithHttpInfo(threadId = threadId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MessengerThreadSummary
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/messenger/threads/{threadId}/join
     * Join a channel-visibility thread in scope (idempotent)
     *
     * @param threadId
     * @return ApiResponse<MessengerThreadSummary?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun joinMessengerThreadWithHttpInfo(threadId: java.util.UUID) : ApiResponse<MessengerThreadSummary?> = withContext(Dispatchers.IO) {
        val localVariableConfig = joinMessengerThreadRequestConfig(threadId = threadId)

        return@withContext request<Unit, MessengerThreadSummary>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation joinMessengerThread
     *
     * @param threadId
     * @return RequestConfig
     */
    fun joinMessengerThreadRequestConfig(threadId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/messenger/threads/{threadId}/join".replace("{"+"threadId"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/messenger/channels
     * List branch-scoped channel threads the caller can see
     *
     * @param limit  (optional, default to 50L)
     * @return MessengerThreadListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listMessengerChannels(limit: kotlin.Long? = 50L) : MessengerThreadListResponse = withContext(Dispatchers.IO) {
        val localVarResponse = listMessengerChannelsWithHttpInfo(limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MessengerThreadListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/messenger/channels
     * List branch-scoped channel threads the caller can see
     *
     * @param limit  (optional, default to 50L)
     * @return ApiResponse<MessengerThreadListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listMessengerChannelsWithHttpInfo(limit: kotlin.Long?) : ApiResponse<MessengerThreadListResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listMessengerChannelsRequestConfig(limit = limit)

        return@withContext request<Unit, MessengerThreadListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listMessengerChannels
     *
     * @param limit  (optional, default to 50L)
     * @return RequestConfig
     */
    fun listMessengerChannelsRequestConfig(limit: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/messenger/channels",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/messenger/threads/{threadId}/presence
     * Presence of the members of a thread
     *
     * @param threadId
     * @return MessengerPresenceListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun messengerThreadPresence(threadId: java.util.UUID) : MessengerPresenceListResponse = withContext(Dispatchers.IO) {
        val localVarResponse = messengerThreadPresenceWithHttpInfo(threadId = threadId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MessengerPresenceListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/messenger/threads/{threadId}/presence
     * Presence of the members of a thread
     *
     * @param threadId
     * @return ApiResponse<MessengerPresenceListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun messengerThreadPresenceWithHttpInfo(threadId: java.util.UUID) : ApiResponse<MessengerPresenceListResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = messengerThreadPresenceRequestConfig(threadId = threadId)

        return@withContext request<Unit, MessengerPresenceListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation messengerThreadPresence
     *
     * @param threadId
     * @return RequestConfig
     */
    fun messengerThreadPresenceRequestConfig(threadId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/messenger/threads/{threadId}/presence".replace("{"+"threadId"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /api/messenger/threads/{threadId}/mute
     * Mute or unmute a thread for the authenticated member
     *
     * @param threadId
     * @param setMessengerThreadMuteRequest
     * @return MessengerThreadSummary
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun setMessengerThreadMute(threadId: java.util.UUID, setMessengerThreadMuteRequest: SetMessengerThreadMuteRequest) : MessengerThreadSummary = withContext(Dispatchers.IO) {
        val localVarResponse = setMessengerThreadMuteWithHttpInfo(threadId = threadId, setMessengerThreadMuteRequest = setMessengerThreadMuteRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MessengerThreadSummary
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /api/messenger/threads/{threadId}/mute
     * Mute or unmute a thread for the authenticated member
     *
     * @param threadId
     * @param setMessengerThreadMuteRequest
     * @return ApiResponse<MessengerThreadSummary?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun setMessengerThreadMuteWithHttpInfo(threadId: java.util.UUID, setMessengerThreadMuteRequest: SetMessengerThreadMuteRequest) : ApiResponse<MessengerThreadSummary?> = withContext(Dispatchers.IO) {
        val localVariableConfig = setMessengerThreadMuteRequestConfig(threadId = threadId, setMessengerThreadMuteRequest = setMessengerThreadMuteRequest)

        return@withContext request<SetMessengerThreadMuteRequest, MessengerThreadSummary>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setMessengerThreadMute
     *
     * @param threadId
     * @param setMessengerThreadMuteRequest
     * @return RequestConfig
     */
    fun setMessengerThreadMuteRequestConfig(threadId: java.util.UUID, setMessengerThreadMuteRequest: SetMessengerThreadMuteRequest) : RequestConfig<SetMessengerThreadMuteRequest> {
        val localVariableBody = setMessengerThreadMuteRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/messenger/threads/{threadId}/mute".replace("{"+"threadId"+"}", encodeURIComponent(threadId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/messenger/messages/{messageId}/ack
     * Toggle the caller&#39;s acknowledgement of a message
     *
     * @param messageId
     * @return MessengerAckSummary
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun toggleMessengerMessageAck(messageId: java.util.UUID) : MessengerAckSummary = withContext(Dispatchers.IO) {
        val localVarResponse = toggleMessengerMessageAckWithHttpInfo(messageId = messageId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MessengerAckSummary
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/messenger/messages/{messageId}/ack
     * Toggle the caller&#39;s acknowledgement of a message
     *
     * @param messageId
     * @return ApiResponse<MessengerAckSummary?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun toggleMessengerMessageAckWithHttpInfo(messageId: java.util.UUID) : ApiResponse<MessengerAckSummary?> = withContext(Dispatchers.IO) {
        val localVariableConfig = toggleMessengerMessageAckRequestConfig(messageId = messageId)

        return@withContext request<Unit, MessengerAckSummary>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation toggleMessengerMessageAck
     *
     * @param messageId
     * @return RequestConfig
     */
    fun toggleMessengerMessageAckRequestConfig(messageId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/messenger/messages/{messageId}/ack".replace("{"+"messageId"+"}", encodeURIComponent(messageId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
