/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.MobileApproveWorkOrderRequest
import com.maintenance.api.client.model.MobileVotePollRequest
import com.maintenance.api.client.model.PollResponse
import com.maintenance.api.client.model.WorkOrderSummary

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class MobileApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/mobile/work-orders/{workOrderId}/approve
     * Approve the next pending approval step from a native mobile client
     * Mobile-scoped approval route. It requires a fresh passkey step-up envelope bound to this work order before the approval mutation or audit side effect runs.
     * @param workOrderId
     * @param mobileApproveWorkOrderRequest
     * @return WorkOrderSummary
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun approveMobileWorkOrder(workOrderId: java.util.UUID, mobileApproveWorkOrderRequest: MobileApproveWorkOrderRequest) : WorkOrderSummary = withContext(Dispatchers.IO) {
        val localVarResponse = approveMobileWorkOrderWithHttpInfo(workOrderId = workOrderId, mobileApproveWorkOrderRequest = mobileApproveWorkOrderRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WorkOrderSummary
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/mobile/work-orders/{workOrderId}/approve
     * Approve the next pending approval step from a native mobile client
     * Mobile-scoped approval route. It requires a fresh passkey step-up envelope bound to this work order before the approval mutation or audit side effect runs.
     * @param workOrderId
     * @param mobileApproveWorkOrderRequest
     * @return ApiResponse<WorkOrderSummary?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun approveMobileWorkOrderWithHttpInfo(workOrderId: java.util.UUID, mobileApproveWorkOrderRequest: MobileApproveWorkOrderRequest) : ApiResponse<WorkOrderSummary?> = withContext(Dispatchers.IO) {
        val localVariableConfig = approveMobileWorkOrderRequestConfig(workOrderId = workOrderId, mobileApproveWorkOrderRequest = mobileApproveWorkOrderRequest)

        return@withContext request<MobileApproveWorkOrderRequest, WorkOrderSummary>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation approveMobileWorkOrder
     *
     * @param workOrderId
     * @param mobileApproveWorkOrderRequest
     * @return RequestConfig
     */
    fun approveMobileWorkOrderRequestConfig(workOrderId: java.util.UUID, mobileApproveWorkOrderRequest: MobileApproveWorkOrderRequest) : RequestConfig<MobileApproveWorkOrderRequest> {
        val localVariableBody = mobileApproveWorkOrderRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/mobile/work-orders/{workOrderId}/approve".replace("{"+"workOrderId"+"}", encodeURIComponent(workOrderId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/mobile/collaboration/polls/{id}/vote
     * Submit or replace a native mobile poll vote with passkey step-up
     * Mobile-scoped poll vote route. It validates poll lifecycle and option ownership only after a fresh passkey step-up envelope is verified for this poll vote.
     * @param id
     * @param mobileVotePollRequest
     * @return PollResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun voteMobileCollaborationPoll(id: java.util.UUID, mobileVotePollRequest: MobileVotePollRequest) : PollResponse = withContext(Dispatchers.IO) {
        val localVarResponse = voteMobileCollaborationPollWithHttpInfo(id = id, mobileVotePollRequest = mobileVotePollRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PollResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/mobile/collaboration/polls/{id}/vote
     * Submit or replace a native mobile poll vote with passkey step-up
     * Mobile-scoped poll vote route. It validates poll lifecycle and option ownership only after a fresh passkey step-up envelope is verified for this poll vote.
     * @param id
     * @param mobileVotePollRequest
     * @return ApiResponse<PollResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun voteMobileCollaborationPollWithHttpInfo(id: java.util.UUID, mobileVotePollRequest: MobileVotePollRequest) : ApiResponse<PollResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = voteMobileCollaborationPollRequestConfig(id = id, mobileVotePollRequest = mobileVotePollRequest)

        return@withContext request<MobileVotePollRequest, PollResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation voteMobileCollaborationPoll
     *
     * @param id
     * @param mobileVotePollRequest
     * @return RequestConfig
     */
    fun voteMobileCollaborationPollRequestConfig(id: java.util.UUID, mobileVotePollRequest: MobileVotePollRequest) : RequestConfig<MobileVotePollRequest> {
        val localVariableBody = mobileVotePollRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/mobile/collaboration/polls/{id}/vote".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
